const allKinkLinkCards = [
    

  // --- TEMA: VOYEURISMO ONLINE / EXIBICIONISMO DE "PESSOAS REAIS" ---
  { id: 'c500', text: 'Olhar juntos fotos de pessoas em comentários de lojas online.', category: 'exposicao', intensity: 1 },
  { id: 'c501', text: 'Postar uma foto sua (mulher) vestindo uma lingerie sexy em comentário de loja online (rosto oculto).', category: 'exposicao', intensity: 3 },
  { id: 'c502', text: 'Parceiro incentiva/ajuda a parceira a tirar e postar fotos sensuais em comentários de lojas.', category: 'exposicao', intensity: 3 },
  { id: 'c503', text: 'Casal escolhe roupa sexy, tira fotos da parceira e posta anonimamente para excitar estranhos.', category: 'fantasia', intensity: 2 },
  { id: 'c504', text: 'Criar um perfil anônimo para postar fotos ousadas suas e interagir com admiradores.', category: 'exposicao', intensity: 4 },

  // --- TEMA: LAMBUZAR / SECREÇÕES CORPORAIS (INTENSIDADE 7-8) ---
  { id: 'c505', text: 'Fetiche em leite materno (lactofilia): parceiro bebe o leite diretamente dos seios da parceira lactante.', category: 'sensorial', intensity: 7 },
  { id: 'c506', text: 'Lambuzar o corpo do(a) parceiro(a) com saliva durante os preliminares.', category: 'sensorial', intensity: 7 },
  { id: 'c507', text: 'Cuspir na boca do(a) parceiro(a) submisso(a) como ato de dominação.', category: 'poder', intensity: 8 },
  { id: 'c508', text: 'Gostaria de ser "lambuzado(a)" com os fluidos de um(a) ou mais parceiros(as).', category: 'sensorial', intensity: 7 },
  { id: 'c509', text: 'Receber "chuva dourada" (golden shower) do(a) parceiro(a).', category: 'sensorial', intensity: 8 },
  { id: 'c510', text: 'Gostaria de dar uma "chuva dourada" (golden shower) no meu/minha parceiro(a).', category: 'poder', intensity: 8 },
  { id: 'c511', text: 'Participar de uma "chuva dourada" com parceiro(a) e um(a) terceiro(a).', category: 'exposicao', intensity: 8 },
  { id: 'c512', text: 'Participar de uma orgia de "chuva dourada" com um grupo.', category: 'exposicao', intensity: 8 },

  // --- TEMA: THREESOME HARD / ANILINGUS PÓS-ANAL ---
  { id: 'c513', text: 'Fazer sexo a três (MMF) com foco na exploração sem limites.', category: 'fantasia', intensity: 6 },
  { id: 'c514', text: 'Fazer sexo a três (MFF) com foco na exploração sem limites.', category: 'fantasia', intensity: 6 },
  { id: 'c515', text: 'Após sexo anal com um(a) parceiro(a), fazer sexo oral no pênis ("sujo").', category: 'poder', intensity: 7 },
  { id: 'c516', text: 'Em um MMF, o homem come a parceira A e em seguida a parceira B chupa seu pênis.', category: 'fantasia', intensity: 8 },
  { id: 'c517', text: 'Explorar o fetiche de "ass to mouth" (do ânus para a boca) entre o casal.', category: 'poder', intensity: 7 },
  { id: 'c518', text: 'Gostaria de experimentar o gosto do ânus do(a) meu/minha parceiro(a) (anilingus).', category: 'sensorial', intensity: 7 },
  { id: 'c519', text: 'Gostaria que meu/minha parceiro(a) fizesse anilingus em mim.', category: 'sensorial', intensity: 7 },
  { id: 'c520', text: 'Praticar anilingus mútuo (69 anal).', category: 'sensorial', intensity: 7 },
  { id: 'c521', text: 'Fazer anilingus em um(a) terceiro(a) a pedido do(a) parceiro(a).', category: 'poder', intensity: 8 },

  // --- TEMA: MORDER / SER MORDIDO (DACNOFILIA) ---
  { id: 'c522', text: 'Gostaria de receber mordidas fortes (deixando marcas) durante o sexo.', category: 'sensorial', intensity: 4 },
  { id: 'c523', text: 'Gostaria de dar mordidas fortes (deixando marcas) no meu/minha parceiro(a).', category: 'sensorial', intensity: 4 },
  { id: 'c524', text: 'Trocar mordidas durante o sexo, como uma forma de comunicação selvagem.', category: 'sensorial', intensity: 4 },
  { id: 'c525', text: 'Morder ou ser mordido(a) por um(a) terceiro(a) durante um ménage.', category: 'sensorial', intensity: 5 },

  // --- TEMA: SUBMISSÃO COMPORTAMENTAL / FUSÃO DE IDENTIDADE ---
  { id: 'c526', text: 'Submeter-me ao estilo de vida do(a) parceiro(a) por um dia (músicas, comidas, hobbies).', category: 'poder', intensity: 3 },
  { id: 'c527', text: 'Gostaria que parceiro(a) me guiasse em seu estilo de vida por uma semana, como aprendiz.', category: 'poder', intensity: 4 },
  { id: 'c528', text: 'Roleplay: Mestre(a) molda seu/sua discípulo(a) em todos os aspectos, não só sexualmente.', category: 'fantasia', intensity: 5 },
  { id: 'c529', text: 'Entregar o controle de minhas redes sociais/playlists ao(à) parceiro(a) dominante por um dia.', category: 'poder', intensity: 3 },
  { id: 'c530', text: 'Ser "reprogramado(a)" pelo(a) parceiro(a) dominante através de repetição e treinamento.', category: 'poder', intensity: 6 },

  // --- TEMA: PLUG ANAL EM PÚBLICO ---
  { id: 'c531', text: 'Usar um plug anal discreto durante as tarefas do dia a dia.', category: 'exposicao', intensity: 2 },
  { id: 'c532', text: 'Ir para a academia usando um plug anal.', category: 'exposicao', intensity: 3 },
  { id: 'c533', text: 'Ir a um encontro usando um plug anal vibratório controlado pelo(a) parceiro(a).', category: 'exposicao', intensity: 4 },
  { id: 'c534', text: 'Fazer uma trilha ou caminhada no parque usando um plug anal.', category: 'exposicao', intensity: 3 },
  { id: 'c535', text: 'Usar um plug anal na casa de amigos/família, sem que ninguém (além do parceiro) saiba.', category: 'exposicao', intensity: 4 },

  // --- TEMA: CONVERSAS ERÓTICAS / CIBERSEXO ---
  { id: 'c536', text: 'Ter uma noite dedicada apenas a "sexting" e troca de nudes, mesmo no mesmo cômodo.', category: 'fantasia', intensity: 2 },
  { id: 'c537', text: 'Gostaria de receber uma ligação/áudio do(a) parceiro(a) narrando uma fantasia erótica.', category: 'fantasia', intensity: 2 },
  { id: 'c538', text: 'Controlar o vibrador do(a) parceiro(a) à distância (teledildonics) enquanto conversam por vídeo.', category: 'poder', intensity: 4 },
  { id: 'c539', text: 'Participar de um chat erótico em grupo com o(a) parceiro(a) e amigos.', category: 'exposicao', intensity: 5 },
  { id: 'c540', text: 'Criar um personagem/avatar e ter uma noite de cibersexo com o(a) parceiro(a) (também como personagem).', category: 'fantasia', intensity: 3 },
  
  // --- TEMA: CNC SIMULADO (PRESA NA ÁRVORE, ETC.) ---
  { id: 'c541', text: 'Roleplay: Ser "encontrada(o)" amarrado(a) e vulnerável na mata pelo(a) parceiro(a), que "se aproveita".', category: 'fantasia', intensity: 4 },
  { id: 'c542', text: 'Roleplay CNC: Amarrada(o) à árvore, "implorar" por ajuda a um "estranho" (amigo) que realiza suas fantasias.', category: 'fantasia', intensity: 5 },
  { id: 'c543', text: 'Roleplay CNC: Amarrada(o) à árvore, ser "encontrada(o)" por um grupo (amigos) que "usa e abusa".', category: 'fantasia', intensity: 6 },
  { id: 'c544', text: 'Roleplay CNC Invertido: O(A) "captor(a)" é surpreendido(a) e dominado(a) pela "vítima".', category: 'poder', intensity: 5 },

  // --- TEMA: APOSTAS E PRÊMIOS ---
  { id: 'c545', text: 'Apostar prendas sexuais em um jogo de cartas/tabuleiro (casal).', category: 'fantasia', intensity: 2 },
  { id: 'c546', text: 'Após perder aposta para parceiro(a), ser o "prêmio" sexual dele(a).', category: 'poder', intensity: 3 },
  { id: 'c547', text: 'Ser o "prêmio" sexual para o vencedor de aposta entre parceiro(a) e amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c548', text: 'Marido me "aposta" em jogo com amigo(a); se perder, cumpro desejo sexual do(a) amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c549', text: 'Esposa me "aposta" em jogo com amigo(a); se perder, cumpro desejo sexual do(a) amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c550', text: 'Em jogo com amigos, o casal concorda que a parceira será "compartilhada" com o vencedor.', category: 'exposicao', intensity: 6 },
  { id: 'c551', text: 'Apostar o(a) parceiro(a) (homem/mulher) em jogo com grupo; perdedor(a) satisfaz o grupo.', category: 'exposicao', intensity: 6 },
  { id: 'c552', text: 'A parceira é oferecida como "prêmio" para o time do parceiro (e amigos) se vencerem um jogo (encenado).', category: 'fantasia', intensity: 6 },

  // --- TEMA: TROCA DE CASAIS / DINÂMICAS DE GRUPO ---
  { id: 'c553', text: 'Roleplay "Troca de Casais": Casal A troca parceiros com Casal B por uma noite.', category: 'fantasia', intensity: 6 },
  { id: 'c554', text: 'Roleplay "Saindo Juntos": Após encontro, os dois casais vão para o mesmo lugar para uma noite de sexo em grupo.', category: 'fantasia', intensity: 6 },
  { id: 'c555', text: 'Roleplay "Adoção de Parceiro": Um casal "adota" um membro de outro casal para uma experiência a três.', category: 'fantasia', intensity: 5 },
  { id: 'c556', text: 'Roleplay "Sequestro de Parceiro": Um casal "sequestra" consensualmente um(a) de vocês para uma noite de "cativeiro" sensual.', category: 'fantasia', intensity: 5 },
  { id: 'c557', text: 'Roleplay "Minha Escrava, Sirva-se": Dominante apresenta parceiro(a) submisso(a) a um(a) convidado(a) para seu uso.', category: 'fantasia', intensity: 6 },
  { id: 'c558', text: 'Roleplay CNC: Marido "forçado" a assistir "invasor" (amigo) tomar sua esposa (encenado).', category: 'fantasia', intensity: 6 },

  // --- TEMA: PROVADORES DE LOJA ---
  { id: 'c559', text: 'Provador: Tirar foto de lingerie e enviar para o(a) parceiro(a) que espera fora.', category: 'exposicao', intensity: 2 },
  { id: 'c560', text: 'Provador: Tirar foto de lingerie e enviar para um(a) amigo(a) pedindo opinião.', category: 'exposicao', intensity: 3 },
  { id: 'c561', text: 'Provador: Entrar com parceiro(a) para "ajudar" a vestir e trocar carícias rápidas.', category: 'exposicao', intensity: 3 },
  { id: 'c562', text: 'Provador: Entrar com um(a) amigo(a) para "ajudar" a escolher, aumentando a tensão sexual.', category: 'exposicao', intensity: 4 },
  { id: 'c563', text: 'Provador: Filmar um strip-tease rápido e enviar para o(a) parceiro(a).', category: 'exposicao', intensity: 2 },
  
  // --- TEMA: HOTWIFE CHALLENGES ---
  { id: 'c564', text: 'Hotwife Challenge: Beijar um(a) estranho(a) em um bar ou festa.', category: 'exposicao', intensity: 4 },
  { id: 'c565', text: 'Hotwife Challenge: Dançar de forma provocante com um(a) estranho(a).', category: 'exposicao', intensity: 4 },
  { id: 'c566', text: 'Hotwife Challenge: Deixar um(a) estranho(a) pagar uma bebida e flertar por 15 minutos.', category: 'exposicao', intensity: 3 },
  { id: 'c567', text: 'Hotwife Challenge: Voltar para casa com o número de telefone de um(a) estranho(a).', category: 'exposicao', intensity: 3 },
  { id: 'c568', text: 'Hotwife Challenge: Ir a um encontro com outra pessoa.', category: 'exposicao', intensity: 5 },
  { id: 'c569', text: 'Hotwife Challenge: Fazer sexo oral em um(a) estranho(a) em uma festa.', category: 'exposicao', intensity: 6 },
  { id: 'c570', text: 'Hotwife Challenge: Voltar para casa com a roupa íntima de um(a) estranho(a).', category: 'exposicao', intensity: 5 },
  { id: 'c571', text: 'Parceira volta para casa com o preservativo usado com outro homem para o marido.', category: 'poder', intensity: 8 },

  // --- TEMA: OBJETIFICAÇÃO / HUMILHAÇÃO CONSENSUAL ---
  { id: 'c572', text: 'Ser banhado(a) pelo(a) parceiro(a) como um objeto ou brinquedo sujo.', category: 'poder', intensity: 4 },
  { id: 'c573', text: 'Servir bebidas ao(à) parceiro(a) dominante usando meu corpo como "bandeja".', category: 'poder', intensity: 4 },
  { id: 'c574', text: 'Servir de "apoio de pés" para o(a) parceiro(a) dominante.', category: 'poder', intensity: 2 },
  { id: 'c575', text: 'No pet play, ser "exibido(a)" pelo(a) "dono(a)" a um(a) amigo(a) como seu "bichinho premiado".', category: 'poder', intensity: 5 },
  { id: 'c576', text: 'Submisso(a) deve comer sua refeição no chão, como um animal, sob ordens do(a) dominante.', category: 'poder', intensity: 4 },

  // --- VARIANTES E EXPANSÕES (de c500+) ---
  { id: 'c577', text: 'Casal cria perfil anônimo e posta fotos sensuais juntos para excitar estranhos.', category: 'exposicao', intensity: 3 },
  { id: 'c578', text: 'Postar foto ousada sua em um grupo fechado de amigos com consentimento do(a) parceiro(a).', category: 'exposicao', intensity: 4 },
  { id: 'c579', text: 'Parceira faz ensaio sensual online para um "fã" específico (amigo combinado) enquanto parceiro assiste/dirige.', category: 'exposicao', intensity: 5 },
  { id: 'c580', text: 'Fetiche em leite materno (lactofilia): parceira lactante amamenta o(a) parceiro(a) e um(a) amigo(a).', category: 'sensorial', intensity: 8 },
  { id: 'c581', text: 'Fetiche em suor: lamber o suor do corpo do(a) parceiro(a) após exercício ou sexo intenso.', category: 'sensorial', intensity: 7 },
  { id: 'c582', text: 'Ser cuspido(a) por ambos os parceiros(as) de um casal convidado.', category: 'poder', intensity: 8 },
  { id: 'c583', text: 'Casal dá "chuva dourada" em um(a) terceiro(a) submisso(a).', category: 'poder', intensity: 8 },
  { id: 'c584', text: 'Em um grupo, explorar "daisy chain" de anilingus ou ass-to-mouth.', category: 'exposicao', intensity: 8 },
  { id: 'c585', text: 'Dominante "oferece" o ânus do(a) submisso(a) para um(a) convidado(a) lamber.', category: 'poder', intensity: 8 },
  { id: 'c586', text: 'Casal (mulheres) explora anilingus uma na outra.', category: 'sensorial', intensity: 7 },
  { id: 'c587', text: 'Casal (homens) explora anilingus um no outro.', category: 'sensorial', intensity: 7 },
  { id: 'c588', text: 'Ser "discípulo(a)" de um casal, aprendendo e adotando o estilo de vida de ambos.', category: 'poder', intensity: 5 },
  { id: 'c589', text: 'Ser "reprogramado(a)" por um grupo, seguindo as regras e estilo de vida deles.', category: 'poder', intensity: 6 },
  { id: 'c590', text: 'Gostaria de moldar completamente o comportamento de um(a) submisso(a) (parceiro(a)).', category: 'poder', intensity: 5 },
  { id: 'c591', text: 'Usar plug anal com controle remoto e entregar o controle para um(a) amigo(a) durante um passeio.', category: 'exposicao', intensity: 5 },
  { id: 'c592', text: 'Em festa íntima, usar plug anal com controle remoto e deixar o controle passar de mão em mão.', category: 'exposicao', intensity: 6 },
  { id: 'c593', text: 'Roleplay: Amarrado(a) na mata, ser "resgatado(a)" por amigo(a) cúmplice do(a) parceiro(a) que participa do "abuso".', category: 'fantasia', intensity: 6 },
  { id: 'c594', text: 'Ser amarrado(a) em local de trilha com pouco movimento (parceiro vigia de longe).', category: 'exposicao', intensity: 4 },
  { id: 'c595', text: 'Ser usado(a) numa trilha, vendado(a), sem saber se quem toca é o(a) parceiro(a) ou um(a) convidado(a).', category: 'fantasia', intensity: 5 },
  { id: 'c596', text: 'Apostar a si mesmo(a) em um jogo contra um casal de amigos. Se perder, você os serve.', category: 'poder', intensity: 6 },
  { id: 'c597', text: 'Apostar o(a) parceiro(a) contra um casal de amigos. Se perder, ele(a) os serve.', category: 'poder', intensity: 6 },
  { id: 'c598', text: 'Casal aposta qual dos dois servirá sexualmente um(a) amigo(a) convidado(a).', category: 'fantasia', intensity: 5 },
  { id: 'c599', text: 'Ser o "prêmio" de uma competição esportiva entre o time do(a) parceiro(a) e amigos.', category: 'exposicao', intensity: 6 },
  { id: 'c600', text: 'Filmar o sexo do casal e depois convidar o(a) amigo(a) cinegrafista para se juntar.', category: 'exposicao', intensity: 5 },
  { id: 'c601', text: 'Filmar o sexo do casal e depois o(a) cinegrafista se junta com sua parceira para uma troca.', category: 'exposicao', intensity: 6 },
  { id: 'c602', text: 'Ménage com poder e humilhação: dominante força submisso(a) a realizar atos em um(a) terceiro(a).', category: 'poder', intensity: 6 },
  { id: 'c603', text: 'Troca de casais onde uma das mulheres é o centro das atenções de todos os outros (FFF+M).', category: 'fantasia', intensity: 6 },
  { id: 'c604', text: 'Troca de casais onde um dos homens é o centro das atenções de todos os outros (MMM+F).', category: 'fantasia', intensity: 6 },
  { id: 'c605', text: 'Entrar com parceiro(a) em provador de loja e deixar a cortina entreaberta.', category: 'exposicao', intensity: 4 },
  { id: 'c606', text: 'Tirar nudes no provador e enviar para um grupo de amigos.', category: 'exposicao', intensity: 4 },
  { id: 'c607', text: 'Ser filmado(a) pelo(a) parceiro(a) experimentando lingerie no provador e enviar para um(a) amigo(a) "avaliar".', category: 'exposicao', intensity: 4 },
  { id: 'c608', text: 'Hotwife Challenge: Flertar com um casal em um bar e conseguir um beijo de ambos.', category: 'exposicao', intensity: 5 },
  { id: 'c609', text: 'Hotwife Challenge: Fazer sexo com um casal de amigos, enquanto o parceiro assiste.', category: 'exposicao', intensity: 6 },
  { id: 'c610', text: 'Hotwife Challenge: Ser a "surpresa" em uma despedida de solteiro de um amigo.', category: 'exposicao', intensity: 6 },
  { id: 'c611', text: 'Ser banhado(a) por um grupo de "donos(as)" como um animal de estimação premiado.', category: 'poder', intensity: 6 },
  { id: 'c612', text: 'Em uma festa, meu corpo ser usado como bandeja de aperitivos para os convidados.', category: 'exposicao', intensity: 5 },
  { id: 'c613', text: 'Receber ordens humilhantes de um(a) convidado(a), com permissão do(a) parceiro(a) dominante.', category: 'poder', intensity: 5 },
  { id: 'c614', text: 'Ter que ficar de quatro e latir/miar para os convidados em uma festa íntima, se ordenado.', category: 'poder', intensity: 5 },
  { id: 'c615', text: 'Escrever no meu corpo uma contagem de quantos parceiros(as) me usaram em uma festa de swing.', category: 'exposicao', intensity: 6 },

  // --- META-KINK e NOVOS CENÁRIOS (c616 - c661) ---
  { id: 'c616', text: 'Meta-Kink: Deixe parceiro(a) escolher uma carta dos seus "Favoritos" para ser realizada este fim de semana.', category: 'fantasia', intensity: 3 },
  { id: 'c617', text: 'Meta-Kink: Peguem a última carta de PODER que deu match e invertam os papéis.', category: 'poder', intensity: 5 },
  { id: 'c618', text: 'Meta-Kink: Cada um escolhe 3 cartas dos "Matches" de Poder. Negociem e realizem uma delas, mas com os papéis invertidos.', category: 'fantasia', intensity: 4 },
  { id: 'c619', text: 'Meta-Kink: Realizar 3 cartas da categoria SENSORIAL em sequência, criando uma jornada de sensações.', category: 'sensorial', intensity: 2 },
  { id: 'c620', text: 'Meta-Kink: Combinem uma fantasia complexa usando apenas o chat desta carta. Nenhuma palavra pessoalmente.', category: 'fantasia', intensity: 4 },
  { id: 'c621', text: 'Freeuse (Casal): Por 24h, meu corpo é de uso livre para você, a qualquer momento e lugar em casa.', category: 'poder', intensity: 5 },
  { id: 'c622', text: 'Freeuse (+1): Acertar via chat os termos para eu ser "freeuse" para você e um(a) amigo(a) por uma noite.', category: 'poder', intensity: 6 },
  { id: 'c623', text: 'Freeuse (Grupo): Ser a "pessoa de uso livre" de uma festa íntima com amigos.', category: 'poder', intensity: 6 },
  { id: 'c624', text: 'Freeuse Invertido: Gostaria de ter meu/minha parceiro(a) como "uso livre" para mim por 24h.', category: 'poder', intensity: 5 },
  { id: 'c625', text: 'Em um momento de paixão, rasgar uma peça de roupa barata (camiseta, meia-calça) do(a) parceiro(a).', category: 'sensorial', intensity: 3 },
  { id: 'c626', text: 'Roleplay de ataque simulado onde a roupa da "vítima" é rasgada pelo(a) "agressor(a)".', category: 'fantasia', intensity: 4 },
  { id: 'c627', text: 'Ter uma peça de roupa íntima (calcinha/cueca) rasgada do corpo pelo(a) parceiro(a) e um(a) convidado(a).', category: 'exposicao', intensity: 5 },
  { id: 'c628', text: 'Comprar roupas em um brechó especificamente para serem rasgadas durante o sexo.', category: 'fantasia', intensity: 2 },
  { id: 'c629', text: 'Receber uma massagem erótica nos pés com óleos quentes.', category: 'sensorial', intensity: 3 },
  { id: 'c630', text: 'Fazer "footjob" (masturbação com os pés) no(a) parceiro(a).', category: 'sensorial', intensity: 3 },
  { id: 'c631', text: 'Ser forçado(a) a lamber e limpar os sapatos/pés do(a) parceiro(a) dominante.', category: 'poder', intensity: 4 },
  { id: 'c632', text: 'Ter os pés adorados por um(a) convidado(a) enquanto o(a) parceiro(a) assiste.', category: 'exposicao', intensity: 4 },
  { id: 'c633', text: 'Usar os pés para provocar o(a) parceiro(a) por baixo da mesa em um restaurante.', category: 'exposicao', intensity: 2 },
  { id: 'c634', text: 'Casal explora adoração de pés com um(a) terceiro(a) (MFF/MMF).', category: 'fantasia', intensity: 5 },
  { id: 'c635', text: 'Roleplay: Um(a) de vocês é caminhoneiro(a) e o(a) outro(a) uma "carona" que oferece pagamento alternativo.', category: 'fantasia', intensity: 3 },
  { id: 'c636', text: 'Trocar carícias ousadas no banheiro de uma parada de caminhoneiros.', category: 'exposicao', intensity: 4 },
  { id: 'c637', text: 'Parceira usa roupa provocante e flerta com caminhoneiros (apenas flerte) enquanto parceiro observa.', category: 'exposicao', intensity: 3 },
  { id: 'c638', text: 'Explorar uma construção abandonada e fazer sexo rápido em um dos cômodos.', category: 'exposicao', intensity: 4 },
  { id: 'c639', text: 'Sessão de fotos nuas artísticas em uma construção abandonada.', category: 'exposicao', intensity: 3 },
  { id: 'c640', text: 'Roleplay CNC: Um(a) parceiro(a) é "sequestrado(a)" e levado(a) para um cativeiro em uma construção abandonada.', category: 'fantasia', intensity: 5 },
  { id: 'c641', text: 'Tirar uma foto mostrando a lingerie no espelho de um banheiro de bar e enviar para o(a) parceiro(a).', category: 'exposicao', intensity: 2 },
  { id: 'c642', text: 'Entrar na mesma cabine de banheiro em um bar movimentado para beijos e carícias quentes.', category: 'exposicao', intensity: 3 },
  { id: 'c643', text: 'Com um(a) amigo(a) cúmplice, entrar no banheiro oposto e tirar uma foto ousada para o casal.', category: 'exposicao', intensity: 4 },
  { id: 'c644', text: 'Sexo rápido no banheiro de um bar/restaurante.', category: 'exposicao', intensity: 4 },
  { id: 'c645', text: 'Sentir o sol e a brisa no corpo nu em uma praia deserta (casal).', category: 'sensorial', intensity: 1 },
  { id: 'c646', text: 'Nadar nu(a) com o(a) parceiro(a) em águas calmas de uma praia isolada.', category: 'sensorial', intensity: 2 },
  { id: 'c647', text: 'Fazer amor na areia morna de uma praia deserta ao pôr do sol.', category: 'sensorial', intensity: 3 },
  { id: 'c648', text: 'Praticar nudismo em uma praia designada, observando e sendo observado(a) por outros.', category: 'exposicao', intensity: 4 },
  { id: 'c649', text: 'Sexo discreto sob uma canga ou toalha em uma praia de nudismo movimentada.', category: 'exposicao', intensity: 5 },
  { id: 'c650', text: 'Participar de uma "caminhada nudista" em grupo por uma praia isolada.', category: 'exposicao', intensity: 4 },
  { id: 'c651', text: 'Permitir que um(a) amigo(a) fotógrafo(a) faça um ensaio nu artístico do casal em uma praia deserta.', category: 'exposicao', intensity: 4 },
  { id: 'c652', text: 'Orgia consensual em uma praia de nudismo isolada ou durante um evento específico.', category: 'exposicao', intensity: 6 },
  { id: 'c653', text: 'Roleplay "Náufragos Apaixonados": casal redescobre a intimidade em uma praia deserta.', category: 'fantasia', intensity: 2 },
  { id: 'c654', text: 'Roleplay "Adão e Eva no Paraíso": viver a inocência e o desejo em uma praia intocada.', category: 'fantasia', intensity: 2 },
  { id: 'c655', text: 'Parceiro(a) dominante "ordena" que o(a) submisso(a) tire a roupa em uma praia deserta e permaneça nu(a).', category: 'poder', intensity: 3 },
  { id: 'c656', text: 'Em uma praia de nudismo, o(a) dominante "apresenta" o(a) submisso(a) nu(a) a um(a) estranho(a) ou amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c657', text: 'Objetificação: Ser banhado(a) por um grupo de "donos(as)" como um animal de estimação premiado.', category: 'poder', intensity: 6 },
  { id: 'c658', text: 'Exposição: Em uma festa, meu corpo ser usado como bandeja de aperitivos para os convidados.', category: 'exposicao', intensity: 5 },
  { id: 'c659', text: 'Humilhação: Receber ordens humilhantes de um(a) convidado(a), com permissão do(a) parceiro(a) dominante.', category: 'poder', intensity: 5 },
  { id: 'c660', text: 'Pet Play: Ter que ficar de quatro e latir/miar para os convidados em uma festa íntima, se ordenado.', category: 'poder', intensity: 5 },
  { id: 'c661', text: 'Escrita Corporal: Escrever no meu corpo uma contagem de quantos parceiros(as) me usaram em uma festa de swing.', category: 'exposicao', intensity: 6 },
  { id: 'c662', text: 'Casal (mulheres) explora anilingus uma na outra.', category: 'sensorial', intensity: 7 }, // Repetida/Refinada de c586
  { id: 'c663', text: 'Casal (homens) explora anilingus um no outro.', category: 'sensorial', intensity: 7 }, // Repetida/Refinada de c587
  { id: 'c664', text: 'Hot-Husband Challenge: Conseguir o número de telefone de uma mulher e mostrar para a esposa.', category: 'exposicao', intensity: 3 },
  { id: 'c665', text: 'Cuckold Challenge: Marido é provocado pela esposa e seu/sua amante (homem ou mulher).', category: 'fantasia', intensity: 5 },
  { id: 'c666', text: 'Objetificação: Usar o corpo do(a) parceiro(a) como um "móvel humano" (apoio de copo, etc.).', category: 'poder', intensity: 4 },
  { id: 'c667', text: 'Em uma festa, parceira dominante "oferece" seu parceiro submisso para servir bebidas aos convidados.', category: 'poder', intensity: 5 },
  { id: 'c668', text: 'Em uma festa, parceiro dominante "oferece" sua parceira submissa para servir bebidas aos convidados.', category: 'poder', intensity: 5 },
  { id: 'c669', text: 'Cenário (Academia): Trocar "ajuda" em exercícios de alongamento que se tornam carícias íntimas em um canto reservado.', category: 'exposicao', intensity: 3 },
  { id: 'c670', text: 'Meta-Kink (Exposição + Poder): Realizar uma tarefa de PODER em um local de EXPOSIÇÃO.', category: 'fantasia', intensity: 6 },
  { id: 'c671', text: 'Humilhação Consensual: Ser "forçado(a)" a usar uma fantasia ridícula ou infantil em uma cena íntima.', category: 'poder', intensity: 3 },
  { id: 'c672', text: 'Humilhação Consensual: Ter uma fantasia ou segredo íntimo revelado a um(a) amigo(a) pelo(a) parceiro(a) dominante.', category: 'poder', intensity: 5 },
  { id: 'c673', text: 'Troca de Casais (Soft): Sair com outro casal para uma noite de dança e flerte, com permissão para beijos e carícias entre todos.', category: 'exposicao', intensity: 4 },
  { id: 'c736', text: 'Amigo Filma: Pedir para um(a) amigo(a) de confiança fazer um ensaio fotográfico nu e sensual do casal.', category: 'exposicao', intensity: 4 },
  { id: 'c737', text: 'Podofilia (Poder): Submisso(a) deve ficar de joelhos e limpar a sola dos sapatos do(a) dominante com a língua.', category: 'poder', intensity: 5 },
  { id: 'c738', text: 'Escrever no corpo do(a) parceiro(a) uma mensagem ousada que ficará visível se uma peça de roupa se mover.', category: 'exposicao', intensity: 3 },
  { id: 'c739', text: 'Orgia em uma praia de nudismo isolada ou durante um evento específico.', category: 'exposicao', intensity: 6 },
  { id: 'c740', text: 'Meta-Kink (Chat): O(a) dominante envia uma ordem pelo chat da carta, o(a) submisso(a) tem 1 hora para cumprir e enviar foto como prova.', category: 'poder', intensity: 4 },
  { id: 'c741', text: 'Humilhação Consensual: O(A) dominante escolhe um apelido degradante para o(a) submisso(a) usar por uma noite.', category: 'poder', intensity: 3 },
  { id: 'c742', text: 'Objetificação (Carro): Ser "exposto(a)" como um troféu no capô do carro (em local privado/seguro) para o(a) parceiro(a) admirar/fotografar.', category: 'exposicao', intensity: 4 },
  { id: 'c743', text: 'Cenário (Construção Abandonada): Fazer sexo contra uma parede pichada, sentindo a textura áspera na pele.', category: 'sensorial', intensity: 3 },
  { id: 'c744', text: 'Cenário (Parada de Caminhoneiros): Dominante "negocia" seu/sua submisso(a) com um "caminhoneiro" (amigo combinado).', category: 'fantasia', intensity: 5 },
  { id: 'c745', text: 'Cenário (Academia): Um(a) "personal trainer" (parceiro(a)) usa um(a) "cliente" (parceiro(a)) para "demonstrar" exercícios para um(a) terceiro(a).', category: 'exposicao', intensity: 4 },
  { id: 'c746', text: 'Fetiche (Rasgar Roupas): Em uma orgia, as roupas de todos são rasgadas como parte do frenesi inicial.', category: 'exposicao', intensity: 6 },
  { id: 'c747', text: 'Freeuse (Objeto): Por uma noite, ser tratado(a) como um objeto de uso livre, onde seu corpo pode ser movido e posicionado sem sua participação ativa.', category: 'poder', intensity: 5 },
  { id: 'c748', text: 'Podofilia (Grupo): Ter os pés adorados e beijados por um grupo de submissos(as).', category: 'poder', intensity: 6 },
  { id: 'c749', text: 'CNC Simulado: Acordar "amarrado(a)" e descobrir que foi "sequestrado(a)" pelo(a) parceiro(a) para um fim de semana de servidão.', category: 'fantasia', intensity: 5 },
  { id: 'c750', text: 'Meta-Kink (Desafio): O casal mostra sua lista de "Matches" para um casal de amigos e eles escolhem uma fantasia para cada casal realizar.', category: 'fantasia', intensity: 5 }
];

// Exporta o array DIRETAMENTE para que o script de upload possa usá-lo.
module.exports = allKinkLinkCards;