const allKinkLinkCards = [
    
{ id: 'c1', text: 'Intimidade com venda nos olhos entre o casal.', category: 'sensorial', intensity: 1 },
  { id: 'c2', text: 'Casal usa vendas; um(a) amigo(a) observa as reações e o tato mútuo.', category: 'sensorial', intensity: 3 },
  { id: 'c3', text: 'Casal vendado explora-se mutuamente enquanto um grupo pequeno e silencioso observa.', category: 'exposicao', intensity: 5 },
  { id: 'c4', text: 'Gostaria que parceiro(a) usasse um vibrador em mim.', category: 'sensorial', intensity: 2 },
  { id: 'c5', text: 'Gostaria de usar um vibrador no(a) parceiro(a).', category: 'sensorial', intensity: 2 },
  { id: 'c6', text: 'Casal explora vibradores, com um(a) amigo(a) controlando um deles ou sugerindo usos.', category: 'sensorial', intensity: 4 },
  { id: 'c7', text: 'Trocar massagem sensual completa com óleos aromáticos (casal).', category: 'sensorial', intensity: 1 },
  { id: 'c8', text: 'Receber massagem sensual de duas pessoas (parceiro(a) e amigo(a)).', category: 'sensorial', intensity: 4 },
  { id: 'c9', text: 'Massagem sensual coletiva: casal e amigos se massageiam mutuamente.', category: 'sensorial', intensity: 5 },
  { id: 'c10', text: 'Brincar com gelo no corpo um do outro, seguido de beijos quentes.', category: 'sensorial', intensity: 2 },
  { id: 'c11', text: 'Sexo oral usando caldas comestíveis no corpo (casal).', category: 'sensorial', intensity: 2 },
  { id: 'c12', text: 'Casal usa caldas comestíveis um no outro, um(a) convidado(a) prova ou ajuda a "limpar".', category: 'sensorial', intensity: 4 },
  { id: 'c13', text: 'Tomar banho de imersão juntos à luz de velas.', category: 'sensorial', intensity: 1 },
  { id: 'c14', text: 'Explorar mordidas leves e chupões em novas partes do corpo.', category: 'sensorial', intensity: 2 },
  { id: 'c15', text: 'Sexo levemente enebriado (ex: vinho).', category: 'sensorial', intensity: 3 },
  { id: 'c16', text: 'Experimentar preservativos com diferentes texturas ou efeitos.', category: 'sensorial', intensity: 1 },
  { id: 'c17', text: 'Sessão "degustação às cegas": um(a) vendado(a) prova alimentos da pele do(a) outro(a).', category: 'sensorial', intensity: 3 },
  { id: 'c18', text: 'Pintura corporal: usar tintas comestíveis um no outro e "limpar" com beijos.', category: 'sensorial', intensity: 3 },
  { id: 'c19', text: 'Explorar fetiche de pés (podolatria): beijos, lambidas, massagem erótica nos pés.', category: 'sensorial', intensity: 3 },
  { id: 'c20', text: 'Usar mordaça leve (tecido/silicone) para aguçar outros sentidos na relação.', category: 'sensorial', intensity: 3 },
  { id: 'c21', text: 'Experimentar toques com cera de vela BDSM (baixa temperatura) na pele.', category: 'sensorial', intensity: 3 },
  { id: 'c22', text: 'Gostaria de sentir cera morna de vela BDSM escorrendo pelo meu corpo.', category: 'sensorial', intensity: 3 },
  { id: 'c23', text: 'Corpo do(a) parceiro(a) como tela para arte com cera morna de vela BDSM.', category: 'sensorial', intensity: 4 },
  { id: 'c24', text: 'Toques leves com flogger (chicotinho de tiras macias) nas costas/nádegas.', category: 'sensorial', intensity: 3 },
  { id: 'c25', text: 'Gostaria de sentir a estimulação de um riding crop em coxas/nádegas.', category: 'sensorial', intensity: 4 },
  { id: 'c26', text: 'Sentir a ardência controlada de um chicote fino (tawse/single tail).', category: 'sensorial', intensity: 5 },
  { id: 'c27', text: 'Usar prendedores de mamilo (nipple clamps) para aumentar sensibilidade.', category: 'sensorial', intensity: 3 },
  { id: 'c28', text: 'Gostaria de experimentar prendedores de mamilo durante preliminares/sexo.', category: 'sensorial', intensity: 3 },
  { id: 'c29', text: 'Explorar roda de Wartenberg levemente sobre a pele para sensações intensas.', category: 'sensorial', intensity: 4 },
  { id: 'c30', text: 'Receber/aplicar mordidas mais fortes (seguras) em ombros, coxas, nádegas.', category: 'sensorial', intensity: 4 },
  { id: 'c31', text: 'Usar anel peniano para prolongar ereção e intensificar sensações.', category: 'sensorial', intensity: 2 },
  { id: 'c32', text: 'Gostaria que parceiro usasse anel peniano vibratório para estimular meu clitóris/períneo.', category: 'sensorial', intensity: 3 },
  { id: 'c33', text: 'Usar plug anal (pequeno/médio) durante o dia ou preliminares para preenchimento.', category: 'sensorial', intensity: 3 },
  { id: 'c34', text: 'Gostaria de usar plug anal (tamanho a combinar) durante sexo vaginal/oral.', category: 'sensorial', intensity: 4 },
  { id: 'c35', text: 'Utilizar plug anal vibratório (controlado ou não) para novas dimensões de prazer.', category: 'sensorial', intensity: 4 },
  { id: 'c36', text: 'Explorar diferentes texturas (seda, couro, látex) em contato com a pele nua.', category: 'sensorial', intensity: 2 },
  { id: 'c37', text: 'Sexo com olhos vendados e ouvidos tampados, focando apenas no tato e olfato.', category: 'sensorial', intensity: 4 },
  { id: 'c38', text: 'Massagem com pedras quentes e frias, alternando temperaturas no corpo.', category: 'sensorial', intensity: 3 },
  { id: 'c39', text: 'Brincar de "mapa corporal": um desenha no corpo do outro para este adivinhar.', category: 'sensorial', intensity: 1 },
  { id: 'c40', text: 'Usar algemas de pelúcia/seda para restringir movimentos levemente.', category: 'sensorial', intensity: 2 },
  { id: 'c41', text: 'Sexo em slow motion, com atenção máxima a cada toque e respiração.', category: 'sensorial', intensity: 3 },
  { id: 'c42', text: 'Gotejar mel ou chocolate morno em áreas erógenas e lamber lentamente.', category: 'sensorial', intensity: 2 },
  { id: 'c43', text: 'Explorar "knife play" simulado (objeto seguro) para tensão e arrepios.', category: 'sensorial', intensity: 3 },
  { id: 'c44', text: 'Criar trilha sonora sensual para uma noite de amor, deixando a música guiar.', category: 'sensorial', intensity: 2 },
  { id: 'c45', text: 'Banho de espuma juntos, com muitas bolhas e carícias subaquáticas.', category: 'sensorial', intensity: 1 },
  { id: 'c46', text: 'Usar lenço de seda para vendar e depois para acariciar o corpo.', category: 'sensorial', intensity: 2 },
  { id: 'c47', text: 'Sessão de beijos: explorar diferentes tipos e locais por todo o corpo.', category: 'sensorial', intensity: 2 },
  { id: 'c48', text: 'Fazer amor em local diferente da casa (tapete da sala, cozinha).', category: 'sensorial', intensity: 2 },
  { id: 'c49', text: 'Explorar "electroplay" com dispositivo TENS/Violet Wand de baixa intensidade.', category: 'sensorial', intensity: 5 },
  { id: 'c50', text: 'Desafio sensorial: um vendado tenta adivinhar partes do corpo do outro pelo toque/cheiro.', category: 'sensorial', intensity: 2 },
  { id: 'c51', text: 'Usar espelho grande para observar o ato sexual de diferentes ângulos.', category: 'sensorial', intensity: 2 },
  { id: 'c52', text: 'Experimentar "hair pulling" consensual (puxar cabelos levemente) na paixão.', category: 'sensorial', intensity: 3 },
  { id: 'c53', text: 'Trocar massagem sensual usando apenas lábios e língua.', category: 'sensorial', intensity: 3 },
  { id: 'c54', text: 'Criar "ambiente sensorial" (luzes, incenso, música, texturas na cama).', category: 'sensorial', intensity: 2 },
  { id: 'c55', text: 'Explorar a sensação de látex ou couro em contato direto com a pele.', category: 'sensorial', intensity: 4 },
  { id: 'c56', text: 'Gostaria que parceiro(a) sussurrasse fantasias em meu ouvido enquanto me toca.', category: 'sensorial', intensity: 2 },
  { id: 'c57', text: 'Experimentar diferentes tipos de lubrificantes (efeito quente, frio, formigamento).', category: 'sensorial', intensity: 2 },
  { id: 'c58', text: 'Ser alimentado(a) pelo(a) parceiro(a) com os olhos vendados, focando no sabor.', category: 'sensorial', intensity: 1 },
  { id: 'c59', text: 'Dançar colado e nu com o(a) parceiro(a) ao som de música lenta.', category: 'sensorial', intensity: 2 },
  { id: 'c60', text: 'Gostaria de ter meu corpo coberto por algo comestível para ser "devorado(a)".', category: 'sensorial', intensity: 3 },
  { id: 'c61', text: 'Explorar vibrações de celular/massageador em diferentes partes do corpo.', category: 'sensorial', intensity: 1 },
  { id: 'c62', text: 'Receber massagem nos mamilos com óleo ou estimulador específico.', category: 'sensorial', intensity: 3 },
  { id: 'c63', text: 'Brincar com plumas ou espanador macio pelo corpo, causando arrepios.', category: 'sensorial', intensity: 1 },
  { id: 'c64', text: 'Escutar os batimentos cardíacos um do outro após intimidade intensa.', category: 'sensorial', intensity: 1 },
  { id: 'c65', text: 'Experimentar seda ou cetim na pele nua (lençóis, roupas).', category: 'sensorial', intensity: 2 },
  { id: 'c66', text: 'Fazer "degustação" de beijos: com sabores diferentes nos lábios.', category: 'sensorial', intensity: 1 },
  { id: 'c67', text: 'Gostaria de ser amarrado(a) levemente com cordas macias e sentir meu corpo ser explorado.', category: 'sensorial', intensity: 3 },
  { id: 'c68', text: 'Escrever no corpo do(a) parceiro(a) enquanto um(a) amigo(a) observa a "obra de arte".', category: 'sensorial', intensity: 3 },
  { id: 'c69', text: 'Usar cubos de gelo saborizados para sexo oral ou percorrer o corpo.', category: 'sensorial', intensity: 2 },
  { id: 'c70', text: 'Escrever palavras/desenhos eróticos no corpo um do outro com caneta/tinta corporal.', category: 'sensorial', intensity: 2 },
  { id: 'c71', text: 'De olhos vendados, permitir que parceiro(a) explore seu corpo com objeto surpresa.', category: 'sensorial', intensity: 3 },
  { id: 'c72', text: 'Fazer sexo numa cachoeira isolada durante uma trilha (casal).', category: 'sensorial', intensity: 3 },
  { id: 'c73', text: 'Sentir a textura da grama/musgo/terra na pele nua durante intimidade ao ar livre (casal).', category: 'sensorial', intensity: 2 },
  { id: 'c74', text: 'Ouvir sons da natureza como trilha sonora para o sexo em camping/trilha (casal).', category: 'sensorial', intensity: 1 },
  { id: 'c75', text: 'Sentir o suor e calor dos corpos durante treino conjunto seguido de sexo intenso (casal).', category: 'sensorial', intensity: 2 },
  { id: 'c76', text: 'Receber massagem esportiva sensual do(a) parceiro(a) após treino pesado (casal).', category: 'sensorial', intensity: 1 },
  { id: 'c77', text: 'Explorar sensação de diferentes cordas (sisal, algodão, seda) na pele em bondage leve (casal).', category: 'sensorial', intensity: 3 },
  { id: 'c78', text: 'Usar vibrador wand potente para massagem corporal profunda que evolui para prazer (casal).', category: 'sensorial', intensity: 4 },
  { id: 'c79', text: 'Experimentar "fisting" anal ou vaginal (requer muito preparo, lubrificação e consentimento).', category: 'sensorial', intensity: 6 },
  { id: 'c80', text: 'Receber/fazer uma massagem lingam (homem) ou yoni (mulher) focada na energia sexual (casal).', category: 'sensorial', intensity: 4 },
  { id: 'c81', text: 'Brincar com texturas alimentares inusitadas no corpo (sementes, grãos) e depois limpar (casal).', category: 'sensorial', intensity: 2 },
  { id: 'c82', text: 'Fazer sexo em banheira de hidromassagem, aproveitando os jatos d\'água (casal).', category: 'sensorial', intensity: 2 },
  { id: 'c83', text: 'Usar bolas de Ben Wa (kegel balls) durante o dia para aumentar a sensibilidade vaginal.', category: 'sensorial', intensity: 2 },
  { id: 'c84', text: 'Explorar a sensação de um vibrador de bala (bullet) em diversas zonas erógenas.', category: 'sensorial', intensity: 1 },
  { id: 'c85', text: 'Usar um lençol de cetim ou seda na cama para uma noite de sensações deslizantes.', category: 'sensorial', intensity: 1 },
  { id: 'c86', text: 'Tomar um banho demorado juntos, explorando cada parte do corpo com sabonetes e esponjas.', category: 'sensorial', intensity: 1 },
  { id: 'c87', text: 'Fazer "footjob" (masturbação com os pés) um no outro.', category: 'sensorial', intensity: 3 },
  { id: 'c88', text: 'Experimentar a sensação de ter o cabelo lavado sensualmente pelo(a) parceiro(a).', category: 'sensorial', intensity: 1 },
  { id: 'c89', text: 'Usar óleos essenciais com aromas afrodisíacos em difusor durante o sexo.', category: 'sensorial', intensity: 1 },
  { id: 'c90', text: 'Beijar o(a) parceiro(a) com um pedaço de gelo na boca.', category: 'sensorial', intensity: 2 },
  { id: 'c91', text: 'Explorar a sensibilidade da parte interna das coxas com diferentes toques (penas, unhas, língua).', category: 'sensorial', intensity: 2 },
  { id: 'c92', text: 'Fazer competição de quem aguenta mais o "olho no olho" sem desviar, terminando em beijos.', category: 'sensorial', intensity: 1 },
  { id: 'c93', text: 'Usar um vibrador de casal (ex: We-Vibe) durante a penetração para prazer simultâneo.', category: 'sensorial', intensity: 3 },
  { id: 'c94', text: 'Experimentar "edging" (controle do orgasmo) para prolongar o prazer e intensificar o clímax.', category: 'sensorial', intensity: 4 },
  { id: 'c95', text: 'Gostaria de ter meus mamilos sugados/lambidos com intensidade.', category: 'sensorial', intensity: 3 },
  { id: 'c96', text: 'Um parceiro escolhe a posição sexual por uma noite.', category: 'poder', intensity: 1 },
  { id: 'c97', text: 'Um parceiro decide o que o outro veste para um encontro íntimo.', category: 'poder', intensity: 1 },
  { id: 'c98', text: 'Gostaria de dar um comando sensual para parceiro(a) obedecer.', category: 'poder', intensity: 2 },
  { id: 'c99', text: 'Gostaria que parceiro(a) me desse um comando sensual para eu obedecer.', category: 'poder', intensity: 2 },
  { id: 'c100', text: 'Sussurrar ordens ou desejos no ouvido do(a) parceiro(a) durante o sexo.', category: 'poder', intensity: 2 },
  { id: 'c101', text: 'Usar palavras de comando e tom autoritário na intimidade.', category: 'poder', intensity: 3 },
  { id: 'c102', text: 'Um(a) parceiro(a) serve o(a) outro(a) de forma submissa por uma noite.', category: 'poder', intensity: 3 },
  { id: 'c103', text: 'Vendar parceiro(a) submisso(a) e guiá-lo(a) com ordens verbais na cena.', category: 'poder', intensity: 3 },
  { id: 'c104', text: 'Gostaria de ser imobilizado(a) pelo meu/minha parceiro(a) e me submeter.', category: 'poder', intensity: 4 },
  { id: 'c105', text: 'Gostaria de imobilizar meu/minha parceiro(a) e tê-lo(a) à minha mercê.', category: 'poder', intensity: 4 },
  { id: 'c106', text: 'Servir obedientemente ao(à) parceiro(a) e a um(a) convidado(a).', category: 'poder', intensity: 4 },
  { id: 'c107', text: 'Servir obedientemente a um grupo de convidados(as) sob ordens do(a) parceiro(a).', category: 'poder', intensity: 5 },
  { id: 'c108', text: 'Spanking: Aplicar tapas firmes na bunda do(a) parceiro(a).', category: 'poder', intensity: 3 },
  { id: 'c109', text: 'Gostaria de receber tapas firmes na bunda do meu/minha parceiro(a).', category: 'poder', intensity: 3 },
  { id: 'c110', text: 'Receber tapas (spanking) de um(a) terceiro(a) sob comando do(a) parceiro(a).', category: 'poder', intensity: 4 },
  { id: 'c111', text: 'Sessão de spanking em grupo, onde vários aplicam/recebem.', category: 'poder', intensity: 6 },
  { id: 'c112', text: 'Beijar e lamber os pés do(a) parceiro(a) dominante em submissão.', category: 'poder', intensity: 3 },
  { id: 'c113', text: 'Roleplay: Mestre/Mestra severo(a) e estudante dedicado(a) obediente.', category: 'poder', intensity: 4 },
  { id: 'c114', text: 'Roleplay: Ataque simulado, um(a) domina fisicamente o(a) outro(a).', category: 'poder', intensity: 4 },
  { id: 'c115', text: 'Roleplay de Invasão: Um(a) parceiro(a) "invade" e domina o(a) outro(a).', category: 'poder', intensity: 4 },
  { id: 'c116', text: 'Roleplay de Invasão: Um(a) invasor(a) (parceiro(a) ou amigo(a)) domina a moradora.', category: 'poder', intensity: 4 },
  { id: 'c117', text: 'Roleplay de Invasão: Um grupo de invasores domina a(s) morador(as).', category: 'poder', intensity: 6 },
  { id: 'c118', text: 'Roleplay Invasão Invertida: A "vítima" domina o(s) invasor(es).', category: 'poder', intensity: 5 },
  { id: 'c119', text: 'Roleplay: Executivo(a) poderoso(a) exige tarefas eróticas do(a) assistente.', category: 'poder', intensity: 4 },
  { id: 'c120', text: 'Roleplay: Rei/Rainha e seu servo(a) devotado(a) por uma noite.', category: 'poder', intensity: 3 },
  { id: 'c121', text: 'Roleplay: Realeza (Rei/Rainha) é servida por múltiplos servos(as) (parceiro(a) e convidados(as)).', category: 'poder', intensity: 5 },
  { id: 'c122', text: 'Roleplay: Servo(a) (ou grupo de servos) se revolta e subjuga a Realeza.', category: 'poder', intensity: 5 },
  { id: 'c123', text: 'Controle de orgasmo: dominante decide quando o(a) submisso(a) pode gozar.', category: 'poder', intensity: 4 },
  { id: 'c124', text: 'Controle de orgasmo: dominante decide, com um(a) convidado(a) observando.', category: 'poder', intensity: 5 },
  { id: 'c125', text: 'Controle de orgasmo: dominante decide quando o(a) submisso(a) pode gozar na frente de uma plateia.', category: 'poder', intensity: 5 },
  { id: 'c126', text: 'Pet Play: Um(a) parceiro(a) age como pet (gata, cão) para o(a) "dono(a)".', category: 'poder', intensity: 4 },
  { id: 'c127', text: 'Humilhação erótica verbal leve (palavras acordadas entre o casal).', category: 'poder', intensity: 3 },
  { id: 'c128', text: 'Humilhação erótica verbal na frente de um(a) convidado(a) ou pequena plateia.', category: 'poder', intensity: 5 },
  { id: 'c129', text: 'A Rainha (parceira) é servida por seu parceiro e uma ou mais convidadas.', category: 'poder', intensity: 5 },
  { id: 'c130', text: 'Roleplay: Interrogatório intenso com sedução e pressão psicológica.', category: 'poder', intensity: 4 },
  { id: 'c131', text: 'Um(a) parceiro(a) vendado(a) e amarrado(a), provocado(a) pelo(a) outro(a) e um(a) convidado(a).', category: 'poder', intensity: 5 },
  { id: 'c132', text: 'Submisso(a) usa coleira e guia, conduzido(a) pelo(a) dominante.', category: 'poder', intensity: 4 },
  { id: 'c133', text: 'Estabelecer regras rígidas para o(a) submisso(a) por 24h, com punições leves.', category: 'poder', intensity: 4 },
  { id: 'c134', text: 'Um(a) parceiro(a) é o "objeto sexual" do outro por uma noite.', category: 'poder', intensity: 5 },
  { id: 'c135', text: 'Um(a) parceiro(a) é o "objeto sexual" de um grupo por uma noite.', category: 'poder', intensity: 6 },
  { id: 'c136', text: 'Roleplay: Cafetina poderosa (parceira) "gerencia" seu parceiro (ou amiga) para um "cliente".', category: 'poder', intensity: 5 },
  { id: 'c137', text: 'Cenário "escravo(a) de pés": submisso(a) adora os pés do(a) dominante.', category: 'poder', intensity: 3 },
  { id: 'c138', text: 'Dominante controla quando o(a) submisso(a) pode ir ao banheiro por horas.', category: 'poder', intensity: 4 },
  { id: 'c139', text: 'Sessão de "impact play" com diversos instrumentos (palmatória, vara).', category: 'poder', intensity: 5 },
  { id: 'c140', text: 'Um(a) parceiro(a) usa plug anal/vaginal o dia todo como lembrete de submissão.', category: 'poder', intensity: 4 },
  { id: 'c141', text: 'Roleplay de "leilão": um(a) parceiro(a) é "leiloado(a)" para servidão sensual.', category: 'poder', intensity: 5 },
  { id: 'c142', text: 'Submisso(a) escreve carta detalhando sua devoção ao(à) dominante.', category: 'poder', intensity: 2 },
  { id: 'c143', text: 'Linguagem corporal de submissão (cabeça baixa, etc.) ao(à) dominante.', category: 'poder', intensity: 2 },
  { id: 'c144', text: 'Dominante escolhe fantasia "humilhante" (consensual) para o(a) submisso(a) usar.', category: 'poder', intensity: 3 },
  { id: 'c145', text: 'Gostaria de ser objetificado(a) pelo(a) meu/minha parceiro(a) durante o sexo.', category: 'poder', intensity: 4 },
  { id: 'c146', text: 'Gostaria de objetificar meu/minha parceiro(a) durante o sexo, tratando-o(a) como brinquedo.', category: 'poder', intensity: 4 },
  { id: 'c147', text: 'Ser tratado(a) como objeto sexual por convidado(a), sob supervisão do(a) parceiro(a).', category: 'poder', intensity: 5 },
  { id: 'c148', text: 'Ser exposto(a) e objetificado(a) para pequeno grupo de amigos.', category: 'poder', intensity: 6 },
  { id: 'c149', text: 'Dominante escreve palavras de posse/regras no corpo do(a) submisso(a) com caneta/tinta.', category: 'poder', intensity: 4 },
  { id: 'c150', text: 'Dominante "inspeciona" detalhadamente corpo do(a) submisso(a), como objeto.', category: 'poder', intensity: 3 },
  { id: 'c151', text: 'Submisso(a) permanece em posição "decorativa" enquanto dominante faz outras atividades.', category: 'poder', intensity: 3 },
  { id: 'c152', text: 'Forçar submisso(a) a usar roupa reveladora e desconfortável para prazer do(a) dominante (e outros).', category: 'poder', intensity: 4 },
  { id: 'c153', text: 'Sessão de humilhação com tarefas servis e degradantes (leves e consensuais).', category: 'poder', intensity: 4 },
  { id: 'c154', text: 'Dominante narra para submisso(a) (ou para terceiros/plateia) seus "defeitos" de forma erotizada.', category: 'poder', intensity: 5 },
  { id: 'c155', text: 'Um(a) parceiro(a) "treinador(a)" dita todos os exercícios e intensidade para o(a) "atleta" na academia, com recompensas/punições sensuais.', category: 'poder', intensity: 4 },
  { id: 'c156', text: 'Após perder aposta para parceiro(a), ser o "prêmio" sexual dele(a).', category: 'poder', intensity: 3 },
  { id: 'c157', text: 'Ser o "prêmio" sexual para o vencedor de aposta entre parceiro(a) e amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c158', text: 'Marido me "aposta" em jogo com amigo(a); se perder, cumpro desejo do(a) amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c159', text: 'Esposa me "aposta" em jogo com amigo(a); se perder, cumpro desejo do(a) amigo(a).', category: 'poder', intensity: 5 },
  { id: 'c160', text: 'Em jogo de poker com amigos, o casal concorda que a parceira será "compartilhada" com o vencedor.', category: 'poder', intensity: 6 },
  { id: 'c161', text: 'Apostar o(a) parceiro(a) (homem ou mulher) em jogo com grupo; perdedor(a) satisfaz o grupo.', category: 'poder', intensity: 6 },
  { id: 'c162', text: 'Roleplay: Prisioneiro(a) de guerra e seu/sua captor(a) implacável (casal).', category: 'poder', intensity: 4 },
  { id: 'c163', text: 'Roleplay: Prisioneiro(a) é interrogado(a)/usado(a) por dois captores (parceiro(a) e amigo(a)).', category: 'poder', intensity: 5 },
  { id: 'c164', text: 'Roleplay: Prisioneiro(a) é submetido(a) a um grupo de captores implacáveis.', category: 'poder', intensity: 6 },
  { id: 'c165', text: 'Roleplay: Policial "aborda" cidadão(ã) de forma intimidadora/sensual (casal).', category: 'poder', intensity: 3 },
  { id: 'c166', text: 'Gostaria de ser "revistado(a)" minuciosamente por um(a) policial (parceiro(a)).', category: 'poder', intensity: 4 },
  { id: 'c167', text: 'Roleplay: Dois policiais (parceiro(a) e amigo(a)) "abordam" e "revistam" um(a) cidadão(ã) suspeito(a).', category: 'poder', intensity: 5 },
  { id: 'c168', text: 'Roleplay: Grupo de policiais "cerca" e "interroga" agressivamente "suspeitos(as)".', category: 'poder', intensity: 6 },
  { id: 'c169', text: 'Roleplay: "Detetive" interroga "inocente" com pressão psicológica e sedução (casal).', category: 'poder', intensity: 4 },
  { id: 'c170', text: 'Roleplay: "Inocente" é interrogada por dois "detetives" (parceiro(a) e amigo(a)), um "bom", outro "mau".', category: 'poder', intensity: 5 },
  { id: 'c171', text: 'Roleplay: "Inocente" é interrogada por um painel de "investigadores" hostis.', category: 'poder', intensity: 6 },
  { id: 'c172', text: 'Roleplay: "Algoz" aplica "punição" corporal/sensual combinada na "criminosa" (parceira).', category: 'poder', intensity: 4 },
  { id: 'c173', text: 'Gostaria de ser "punido(a)" por parceiro(a) por uma "infração" com spanking/disciplina.', category: 'poder', intensity: 3 },
  { id: 'c174', text: 'Roleplay: "Criminosa" é "punida" pelo(a) "carcereiro(a)" (parceiro(a)) e um(a) "guarda" (amigo(a)).', category: 'poder', intensity: 5 },
  { id: 'c175', text: 'Roleplay: "Criminosa" é submetida a "julgamento" e "punição" por um "tribunal" de amigos.', category: 'poder', intensity: 6 },
  { id: 'c176', text: 'Banhar parceiro(a) meticulosamente, como se preparasse um objeto para uso por um grupo.', category: 'poder', intensity: 5 },
  { id: 'c177', text: 'Servir bebidas ao(à) parceiro(a) dominante e seus convidados usando meu corpo como "bandeja".', category: 'poder', intensity: 5 },
  { id: 'c178', text: 'No pet play, ser "treinado(a)" com "recompensas" e "punições" por um grupo de "donos".', category: 'poder', intensity: 6 },
  { id: 'c179', text: 'Em uma trilha, ser vendado(a) e ter o corpo explorado pelo(a) parceiro(a) e um(a) amigo(a) "guia".', category: 'poder', intensity: 4 },
  { id: 'c180', text: 'Ser "largado(a)" amarrado(a) e vendado(a) na mata (parceiro(a) vigia), com a possibilidade de um "estranho" (amigo) te encontrar.', category: 'poder', intensity: 5 },
  { id: 'c181', text: 'Após vencer aposta, o(a) parceiro(a) e um(a) amigo(a) dividem o "prêmio" (você).', category: 'poder', intensity: 6 },
  { id: 'c182', text: 'Gostaria de ter minhas roupas escolhidas pelo(a) parceiro(a) dominante por uma semana.', category: 'poder', intensity: 3 },
  { id: 'c183', text: 'O(A) parceiro(a) submisso(a) deve andar de quatro pela casa quando ordenado(a).', category: 'poder', intensity: 3 },
  { id: 'c184', text: 'Ser "inspecionado(a)" nu(a) pelo(a) parceiro(a) dominante, que pode apontar "falhas" ou "qualidades".', category: 'poder', intensity: 4 },
  { id: 'c185', text: 'Ser "inspecionado(a)" nu(a) pelo(a) parceiro(a) dominante na frente de um(a) convidado(a).', category: 'poder', intensity: 5 },
  { id: 'c186', text: 'Ser "inspecionado(a)" nu(a) por um grupo liderado pelo(a) parceiro(a) dominante.', category: 'poder', intensity: 6 },
  { id: 'c187', text: 'Usar uma placa com uma frase humilhante (consensual) escolhida pelo(a) dominante, em casa.', category: 'poder', intensity: 3 },
  { id: 'c188', text: 'O(A) dominante pode proibir o(a) submisso(a) de se sentar em móveis, devendo ficar no chão.', category: 'poder', intensity: 2 },
  { id: 'c189', text: 'Ter que pedir permissão ao(à) dominante para todas as atividades básicas (comer, beber).', category: 'poder', intensity: 4 },
  { id: 'c190', text: 'Roleplay: Um(a) parceiro(a) é o(a) "personal trainer" sádico(a) que impõe exercícios exaustivos com conotação sexual.', category: 'poder', intensity: 4 },
  { id: 'c191', text: 'Sessão de "adoração de botas/sapatos": submisso(a) deve limpar e beijar o calçado do(a) dominante.', category: 'poder', intensity: 3 },
  { id: 'c192', text: 'O(A) dominante usa o corpo do(a) submisso(a) como um "móvel humano" (ex: apoio de copo).', category: 'poder', intensity: 4 },
  { id: 'c193', text: 'Forçar o(a) submisso(a) a usar uma roupa ridícula ou infantil durante uma cena.', category: 'poder', intensity: 3 },
  { id: 'c194', text: 'Gostaria de ser "treinado(a)" como um(a) animal de estimação pelo(a) parceiro(a) e um(a) amigo(a) "adestrador(a)".', category: 'poder', intensity: 5 },
  { id: 'c195', text: 'Submisso(a) deve comer sua refeição no chão, como um animal, sob ordens do(a) dominante.', category: 'poder', intensity: 4 },
  { id: 'c196', text: 'O(A) dominante "redecora" o corpo do(a) submisso(a) com maquiagem de forma humilhante ou fetichista.', category: 'poder', intensity: 3 },
  { id: 'c197', text: 'Ser vendado(a) e ter o corpo usado para jogos de "tiro ao alvo" com objetos macios ou comestíveis por parceiro(a) e amigos.', category: 'poder', intensity: 5 },
  { id: 'c198', text: 'Após perder aposta, ser "propriedade" de um grupo de amigos do(a) parceiro(a) por uma hora para cumprir ordens leves.', category: 'poder', intensity: 6 },
  { id: 'c199', text: 'Apostar com o(a) parceiro(a): quem perder, se torna "escravo(a) de apostas" do(a) vencedor(a) por um dia.', category: 'poder', intensity: 3 },
  { id: 'c200', text: 'Em um jogo de cartas com amigos, o(a) parceiro(a) perdedor(a) (do casal) deve obedecer a um comando de cada jogador da mesa.', category: 'poder', intensity: 6 },
  { id: 'c201', text: 'Um(a) parceiro(a) (ou ambos) usa um uniforme de autoridade (policial, militar) e comanda o(a) outro(a) (ou um grupo) durante a noite.', category: 'poder', intensity: 3 },
  { id: 'c202', text: 'Casal pratica "age play": um assume papel infantilizado, outro cuida/disciplina.', category: 'poder', intensity: 4 },
  { id: 'c203', text: 'Casal pratica "age play" com um(a) amigo(a) no papel de "babá" ou "irmão(ã) mais velho(a)" que também disciplina.', category: 'poder', intensity: 5 },
  { id: 'c204', text: 'Ser "castigado(a)" pelo(a) parceiro(a) com isolamento sensorial (venda, tampões) por um tempo determinado.', category: 'poder', intensity: 3 },
  { id: 'c205', text: 'O(A) dominante dita as fantasias que o(a) submisso(a) deve ter e narrar.', category: 'poder', intensity: 4 },

  // --- CATEGORIA: FANTASIA (c206 - c310) ---
  { id: 'c206', text: 'Encenar encontro às cegas com nomes/histórias falsas, seduzindo um ao outro.', category: 'fantasia', intensity: 2 },
  { id: 'c207', text: 'Recriar cena icônica de filme/série, mas com final erótico improvisado.', category: 'fantasia', intensity: 2 },
  { id: 'c208', text: 'Roleplay: Viajante do tempo aparece subitamente com segredo/missão.', category: 'fantasia', intensity: 3 },
  { id: 'c209', text: 'Criar cenário "baile de máscaras" em casa (música, trajes, sedução anônima).', category: 'fantasia', intensity: 2 },
  { id: 'c210', text: 'Roleplay: Detetive particular investiga suspeito(a) charmoso(a), e a investigação torna-se íntima.', category: 'fantasia', intensity: 3 },
  { id: 'c211', text: 'Fantasia "gênio da lâmpada": um parceiro concede três desejos eróticos ao outro.', category: 'fantasia', intensity: 3 },
  { id: 'c212', text: 'Vocês são piratas rivais que se capturam e "negociam" a liberdade sensualmente.', category: 'fantasia', intensity: 4 },
  { id: 'c213', text: 'Roleplay: Astro/estrela de rock e fã que consegue acesso ao backstage.', category: 'fantasia', intensity: 3 },
  { id: 'c214', text: 'Encenar "casamento arranjado", noivos se conhecem na noite de núpcias.', category: 'fantasia', intensity: 3 },
  { id: 'c215', text: 'Personagens de videogame de aventura ganham vida e exploram sensações.', category: 'fantasia', intensity: 2 },
  { id: 'c216', text: 'Escrever um conto erótico colaborativo: um começa, o outro continua.', category: 'fantasia', intensity: 3 },
  { id: 'c217', text: 'Roleplay: Negociação tensa entre chefe da máfia e detetive que vira sedução.', category: 'fantasia', intensity: 4 },
  { id: 'c218', text: 'Escolher país/cultura exótica e criar cenário romântico/sensual inspirado.', category: 'fantasia', intensity: 3 },
  { id: 'c219', text: 'Roleplay "Massagista Profissional" oferece "serviços extras" ao(à) cliente (parceiro(a)).', category: 'fantasia', intensity: 3 },
  { id: 'c220', text: 'Roleplay "Massagista Profissional" atende o casal, oferecendo "serviços extras" a ambos.', category: 'fantasia', intensity: 4 },
  { id: 'c221', text: 'Fantasia: Únicos sobreviventes em mundo pós-apocalíptico redescobrem intimidade.', category: 'fantasia', intensity: 3 },
  { id: 'c222', text: 'Fantasia: Sobreviventes de apocalipse encontram outro(s) sobrevivente(s) para explorar prazer.', category: 'fantasia', intensity: 5 },
  { id: 'c223', text: 'Roleplay: Personal trainer insistente com seu/sua cliente (parceiro(a)).', category: 'fantasia', intensity: 2 },
  { id: 'c224', text: 'Criar "mapa do tesouro" erótico pela casa, com pistas e "estações" de prazer.', category: 'fantasia', intensity: 3 },
  { id: 'c225', text: 'Roleplay: Artista buscando inspiração e seu/sua muso(a) inspirador(a).', category: 'fantasia', intensity: 2 },
  { id: 'c226', text: 'Simular "apagão" em casa, explorando intimidade à luz de velas/lanternas.', category: 'fantasia', intensity: 2 },
  { id: 'c227', text: 'Roleplay: Entrevista de emprego onde entrevistador(a) faz perguntas cada vez mais pessoais/provocantes.', category: 'fantasia', intensity: 4 },
  { id: 'c228', text: 'Roleplay: Entrevista de emprego com um painel de entrevistadores (parceiro(a) e amigos) fazendo perguntas íntimas.', category: 'fantasia', intensity: 5 },
  { id: 'c229', text: 'Encenar "reality show" particular com desafios sensuais para o casal.', category: 'fantasia', intensity: 3 },
  { id: 'c230', text: 'Encenar "reality show" particular com casal e amigos convidados como "jurados" ou "participantes".', category: 'fantasia', intensity: 5 },
  { id: 'c231', text: 'Roleplay: Policial prende suspeito(a) charmoso(a), tensão sexual aumenta no "interrogatório".', category: 'fantasia', intensity: 3 },
  { id: 'c232', text: 'Roleplay: Aluno(a) seduzido(a) por professor(a) mais velho(a).', category: 'fantasia', intensity: 3 },
  { id: 'c233', text: 'Roleplay: Professor(a) seduz aluno(a) e um(a) colega deste(a).', category: 'fantasia', intensity: 4 },
  { id: 'c234', text: 'Roleplay: Professor(a) com sua classe (parceiro(a) e amigos) em "aula prática" de sedução.', category: 'fantasia', intensity: 6 },
  { id: 'c235', text: 'Roleplay: Estranhos em trem/avião iniciam conversa picante e flerte intenso.', category: 'fantasia', intensity: 3 },
  { id: 'c236', text: 'Roleplay: Invasão domiciliar consensual, um "invasor" domina o(a) "morador(a)".', category: 'fantasia', intensity: 4 }, // Movido de Poder para Fantasia se o foco for o cenário/narrativa
  { id: 'c237', text: 'Roleplay: Invasão domiciliar, um invasor (parceiro(a)) domina a moradora com amigo(a) cúmplice.', category: 'fantasia', intensity: 5 },
  { id: 'c238', text: 'Roleplay: Invasão domiciliar, grupo de invasores (parceiro(a) e amigos) domina o(s) morador(es).', category: 'fantasia', intensity: 6 },
  { id: 'c239', text: 'Roleplay: Jornalista entrevista celebridade reclusa, entrevista toma rumo íntimo.', category: 'fantasia', intensity: 3 },
  { id: 'c240', text: 'Roleplay: Contratar "acompanhante de luxo" (parceiro(a)) para noite de sedução.', category: 'fantasia', intensity: 3 },
  { id: 'c241', text: 'Roleplay: Contratar "acompanhante de luxo" (parceiro(a)) e um(a) amigo(a) para noite a três.', category: 'fantasia', intensity: 5 },
  { id: 'c242', text: 'Roleplay: Contratar "acompanhantes de luxo" (parceiro(a) e amigos) para orgia sofisticada.', category: 'fantasia', intensity: 6 },
  { id: 'c243', text: 'Roleplay: Encenar cena de filme romântico famosa, mas com toque erótico original.', category: 'fantasia', intensity: 2 },
  { id: 'c244', text: 'Roleplay: Viagem no tempo, casal se encontra em outra época e explora dinâmica.', category: 'fantasia', intensity: 3 },
  { id: 'c245', text: 'Roleplay: Casal de espiões rivais forçados a trabalhar juntos se rendem à atração.', category: 'fantasia', intensity: 4 },
  { id: 'c246', text: 'Roleplay: Casal de espiões com um(a) terceiro(a) agente duplo(a) em missão sensual.', category: 'fantasia', intensity: 5 },
  { id: 'c247', text: 'Roleplay: Equipe de espiões (casal e amigos) em missão que envolve sedução e sexo em grupo.', category: 'fantasia', intensity: 6 },
  { id: 'c248', text: 'Roleplay: Realeza (rei/rainha) e seu servo(a) leal e devotado(a).', category: 'fantasia', intensity: 3 }, // Foco no cenário, diferente da de Poder
  { id: 'c249', text: 'Roleplay: Realeza é servida por parceiro(a) e um(a) convidado(a) (servo/serva adicional).', category: 'fantasia', intensity: 4 },
  { id: 'c250', text: 'Roleplay: Realeza é servida por toda uma corte de servos (parceiro(a) e grupo).', category: 'fantasia', intensity: 5 },
  { id: 'c251', text: 'Cenário Cuckolding: Marido assiste esposa com convidado.', category: 'fantasia', intensity: 5 },
  { id: 'c252', text: 'Cenário Cuckqueaning: Esposa assiste marido com convidada.', category: 'fantasia', intensity: 5 },
  { id: 'c253', text: 'Cenário "Hotwife": Esposa se diverte com múltiplos homens (amigos) com marido observando/participando.', category: 'fantasia', intensity: 6 },
  { id: 'c254', text: 'Cenário "Stag/Vixen": Marido se diverte com múltiplas mulheres (amigas) com esposa observando/participando.', category: 'fantasia', intensity: 6 },
  { id: 'c255', text: 'Gangbang/Reverse Gangbang simulado ou real: Sexo grupal intenso.', category: 'fantasia', intensity: 6 },
  { id: 'c256', text: 'Roleplay: Terapeuta e paciente, sessão evolui para exploração íntima.', category: 'fantasia', intensity: 4 },
  { id: 'c257', text: 'Fantasia de abdução alienígena com experimentos sexuais lúdicos.', category: 'fantasia', intensity: 4 },
  { id: 'c258', text: 'Roleplay "primeira vez" com parceiro(a) experiente e outro(a) tímido(a).', category: 'fantasia', intensity: 2 },
  { id: 'c259', text: 'Encenar casamento arranjado, noivos se conhecem na noite de núpcias.', category: 'fantasia', intensity: 3 },
  { id: 'c260', text: 'Roleplay "vizinhos curiosos" que se envolvem após encontro "acidental".', category: 'fantasia', intensity: 2 },
  { id: 'c261', text: 'Fantasia: um parceiro é "camgirl/camboy", outro é fã com pedidos especiais.', category: 'fantasia', intensity: 4 },
  { id: 'c262', text: 'Fantasia de "troca de corpos": agir/falar como o outro na intimidade.', category: 'fantasia', intensity: 3 },
  { id: 'c263', text: 'Usar máscaras (venezianas, animais) no sexo para mistério e desinibição.', category: 'fantasia', intensity: 2 },
  { id: 'c264', text: 'Roleplay "Confessionário sensual": um confessa desejos secretos ao outro "confessor".', category: 'fantasia', intensity: 3 },
  { id: 'c265', text: 'Criar "alter ego" sexual para cada um (nome, história) e interagir como eles.', category: 'fantasia', intensity: 4 },
  { id: 'c266', text: 'Roleplay "Garota de Programa no Parque": parceira encena, marido "contrata".', category: 'fantasia', intensity: 4 },
  { id: 'c267', text: 'Roleplay "Garota de Programa no Parque": parceira encena, dois amigos "contratam".', category: 'fantasia', intensity: 5 },
  { id: 'c268', text: 'Roleplay "Garota de Programa no Parque": parceira encena, um grupo "contrata".', category: 'fantasia', intensity: 6 },
  { id: 'c269', text: 'Fantasia "Despedida de Solteiro": esposa é "contratada" para a festa do marido (simulada com amigos).', category: 'fantasia', intensity: 5 },
  { id: 'c270', text: 'Casal finge ser "voyeurs" profissionais observando (e narrando) intimidade de outro casal (imaginário ou amigos).', category: 'fantasia', intensity: 4 },
  { id: 'c271', text: 'Fantasia de "Dirty Scrabble/Palavras Cruzadas": jogar uma versão erótica.', category: 'fantasia', intensity: 1 },
  { id: 'c272', text: 'Encenar "leilão de fantasias": cada um escreve 3, são "leiloadas" com carícias, vencedora é realizada.', category: 'fantasia', intensity: 3 },
  { id: 'c273', text: 'Roleplay "Entrevista com Estrela Pornô": um é a estrela, outro o entrevistador curioso.', category: 'fantasia', intensity: 3 },
  { id: 'c274', text: 'Fantasia de "fotógrafo(a) e modelo nu(a)": criar ensaio sensual caseiro.', category: 'fantasia', intensity: 2 },
  { id: 'c275', text: 'Simular "encontro virtual" em cômodos diferentes, seduzindo por texto/áudio antes do físico.', category: 'fantasia', intensity: 2 },
  { id: 'c276', text: 'Roleplay CNC: Amarrada(o) a árvore, "implorar" ajuda a "estranho" (amigo combinado) que realiza fantasias.', category: 'fantasia', intensity: 5 },
  { id: 'c277', text: 'Roleplay CNC: Amarrada(o) a árvore, ser "encontrada(o)" por grupo (amigos) que "usa e abusa".', category: 'fantasia', intensity: 6 },
  { id: 'c278', text: 'Roleplay: Exploradores perdidos na selva encontram consolo e prazer um no outro.', category: 'fantasia', intensity: 2 },
  { id: 'c279', text: 'Roleplay: Seres da floresta (ninfas, sátiros) seduzem um humano perdido.', category: 'fantasia', intensity: 3 },
  { id: 'c280', text: 'Roleplay: Casal "adota" um(a) parceiro(a) de outro casal amigo para experiência a três, outro observa/junta-se.', category: 'fantasia', intensity: 5 },
  { id: 'c281', text: 'Roleplay: Casal "sequestra" consensualmente um(a) parceiro(a) de outro casal amigo para "cativeiro" sensual.', category: 'fantasia', intensity: 5 },
  { id: 'c282', text: 'Roleplay CNC: Marido imobilizado "forçado" a assistir "invasor" (amigo) tomar sua esposa "à força".', category: 'fantasia', intensity: 6 },
  { id: 'c283', text: 'Esposa "forçada" a assistir parceira lésbica (ou amiga) ser "tomada" por homem (amigo).', category: 'fantasia', intensity: 6 },
  { id: 'c284', text: 'Roleplay: Parceiro(a) é personal trainer que usa métodos "alternativos" para motivar cliente na academia.', category: 'fantasia', intensity: 3},
  { id: 'c285', text: 'Fantasia "acampamento mal-assombrado": sustos e mistério se transformam em tesão na barraca.', category: 'fantasia', intensity: 2 },
  { id: 'c286', text: 'Roleplay: Explorar uma fantasia de "viagem no tempo" para uma noite de bacanal romano/grego com o casal e amigos.', category: 'fantasia', intensity: 6 },
  { id: 'c287', text: 'Cenário de "Clube de Luta Erótico": o casal (ou com amigos) participa de lutas sensuais onde o perdedor serve o vencedor.', category: 'fantasia', intensity: 5 },
  { id: 'c288', text: 'Fantasia de "Show de Mágica Erótico": um é o mágico, o outro o assistente, com truques que envolvem nudez e sedução (pode ter plateia de amigos).', category: 'fantasia', intensity: 4 },
  { id: 'c289', text: 'Roleplay: Um(a) de vocês é um(a) "DJ de festa rave" e o(a) outro(a) (e amigos) são fãs que invadem a cabine para uma "after party" particular.', category: 'fantasia', intensity: 5 },
  { id: 'c290', text: 'Encenar um "Conto das Mil e Uma Noites" com sultão/sultana, odaliscas e eunucos (parceiro(a) e amigos).', category: 'fantasia', intensity: 6 },
  { id: 'c291', text: 'Roleplay "Mecânico(a) Atrevido(a)": Cliente leva carro para oficina, mecânico(a) (parceiro(a)) faz "inspeção" íntima.', category: 'fantasia', intensity: 3 },
  { id: 'c292', text: 'Roleplay "Mecânico(a) e Cliente com Amigo(a)": Cliente leva carro, mecânico(a) e um(a) amigo(a) "avaliam" o(a) cliente.', category: 'fantasia', intensity: 4 },
  { id: 'c293', text: 'Roleplay "Oficina em Grupo": Cliente é "atendido(a)" por um grupo de mecânicos(as) (parceiro(a) e amigos).', category: 'fantasia', intensity: 5 },
  { id: 'c294', text: 'Fantasia "Uber Proibido": Um(a) parceiro(a) é o motorista, o(a) outro(a) o(a) passageiro(a) que oferece "pagamento alternativo".', category: 'fantasia', intensity: 3 },
  { id: 'c295', text: 'Fantasia "Uber com Amigo": Amigo(a) é o motorista, casal se provoca no banco de trás, tentando envolvê-lo(a).', category: 'fantasia', intensity: 4 },
  { id: 'c296', text: 'Roleplay: Um(a) personal trainer (parceiro(a)) "corrige" a postura do(a) cliente (parceiro(a)) com toques íntimos na academia.', category: 'fantasia', intensity: 3 },
  { id: 'c297', text: 'Roleplay: Encontro secreto numa trilha deserta, como amantes proibidos.', category: 'fantasia', intensity: 2 },
  { id: 'c298', text: 'Fantasia de "Adão e Eva" numa praia deserta ou cachoeira.', category: 'fantasia', intensity: 2 },
  { id: 'c299', text: 'Encenar uma "entrevista" para um clube de swing apenas entre o casal, respondendo perguntas picantes.', category: 'fantasia', intensity: 2 },
  { id: 'c300', text: 'Roleplay "Interrogatório Policial Injusto": Uma parceira é a policial durona, o outro o "inocente" que ela tenta seduzir/pressionar.', category: 'fantasia', intensity: 4 }, // Foco feminino no poder
  { id: 'c301', text: 'Roleplay "Punição da Culpada": Uma parceira é a "juíza/algoz", a outra a "criminosa" que recebe uma punição sensual.', category: 'fantasia', intensity: 4 }, // Foco feminino
  { id: 'c302', text: 'Roleplay "Policial Aborda Casal": Policial (amigo) aborda o casal (mulher+homem/mulher) em situação comprometedora e "abusa da autoridade".', category: 'fantasia', intensity: 5 }, // Foco em dinâmica que pode ser interessante para mulheres
  { id: 'c303', text: 'Fantasia de "Figurante em Filme Pornô": O casal finge estar em um set, seguindo "instruções" de um diretor imaginário.', category: 'fantasia', intensity: 3 },
  { id: 'c304', text: 'Roleplay "Chef e Aprendiz": Chef experiente ensina os segredos da culinária (e do prazer) ao(à) jovem aprendiz na cozinha.', category: 'fantasia', intensity: 2 },
  { id: 'c305', text: 'Fantasia de "Escape Room Erótico": Criar enigmas pela casa que levam a recompensas sensuais ao serem resolvidos.', category: 'fantasia', intensity: 3 },

  // --- CATEGORIA: EXPOSIÇÃO (c306 - ...) ---
  { id: 'c306', text: 'Gostaria que parceiro(a) me gravasse em performance sensual privada.', category: 'exposicao', intensity: 1 },
  { id: 'c307', text: 'Sair sem roupa íntima e deixar parceiro(a) saber, provocando-o(a) em público.', category: 'exposicao', intensity: 2 },
  { id: 'c308', text: 'Fazer striptease particular e produzido para o(a) parceiro(a).', category: 'exposicao', intensity: 1 },
  { id: 'c309', text: 'Striptease para o(a) parceiro(a) e um(a) amigo(a) convidado(a).', category: 'exposicao', intensity: 4 },
  { id: 'c310', text: 'Striptease para o(a) parceiro(a) e uma pequena plateia de amigos.', category: 'exposicao', intensity: 5 },
  { id: 'c311', text: 'Deixar porta do banheiro entreaberta "sem querer" no banho com visita em casa.', category: 'exposicao', intensity: 3 },
  { id: 'c312', text: 'Enviar foto sensual (não explícita) para amigo(a) comum, com consentimento do(a) parceiro(a).', category: 'exposicao', intensity: 2 },
  { id: 'c313', text: 'Andar de lingerie/toalha em casa na presença de amigo(a) íntimo(a) convidado.', category: 'exposicao', intensity: 3 },
  { id: 'c314', text: 'Filmar sexo do casal (rostos ocultos/não) e mostrar para amigo(a) de confiança.', category: 'exposicao', intensity: 4 },
  { id: 'c315', text: 'Filmar sexo do casal e mostrar para pequeno grupo seleto de amigos.', category: 'exposicao', intensity: 5 },
  { id: 'c316', text: 'Gostaria que meu/minha parceiro(a) me observasse enquanto me masturbo.', category: 'exposicao', intensity: 2 },
  { id: 'c317', text: 'Masturbar-me para meu/minha parceiro(a) e um(a) amigo(a) convidado(a).', category: 'exposicao', intensity: 4 },
  { id: 'c318', text: 'Masturbar-me para meu/minha parceiro(a) e uma pequena plateia de amigos.', category: 'exposicao', intensity: 5 },
  { id: 'c319', text: 'Sexo em local semi-público com baixo risco de serem vistos (varanda, trilha).', category: 'exposicao', intensity: 3 },
  { id: 'c320', text: 'Ser exibido(a) sensualmente pelo(a) parceiro(a) em videochamada para terceiro(s).', category: 'exposicao', intensity: 4 },
  { id: 'c321', text: 'Parceira se masturba no carro (parado/em movimento seguro) com chance de ser vista.', category: 'exposicao', intensity: 4 },
  { id: 'c322', text: 'Sexo no carro em lava-rápido automático, aproveitando privacidade momentânea.', category: 'exposicao', intensity: 3 },
  { id: 'c323', text: 'Ir a praia de nudismo e praticar nudismo juntos.', category: 'exposicao', intensity: 4 },
  { id: 'c324', text: 'Ir a praia de nudismo com parceiro(a) e um(a) amigo(a), praticando nudismo juntos.', category: 'exposicao', intensity: 4 }, // Adicionado variante +1
  { id: 'c325', text: 'Participar de um evento ou festa nudista em grupo.', category: 'exposicao', intensity: 5 }, // Adicionado variante grupo
  { id: 'c326', text: 'Mandar nudes artísticas para parceiro(a) quando ele(a) estiver ocupado(a).', category: 'exposicao', intensity: 2 },
  { id: 'c327', text: 'Flertar abertamente com frentista/atendente (com cumplicidade do(a) parceiro(a)).', category: 'exposicao', intensity: 2 },
  { id: 'c328', text: 'Sexo no carro em "dogging point", apenas observando outros.', category: 'exposicao', intensity: 4 }, // Variante observação
  { id: 'c329', text: 'Sexo no carro em "dogging point", sendo observado(a) por outros.', category: 'exposicao', intensity: 5 }, // Variante sendo observado
  { id: 'c330', text: 'Sexo no carro em "dogging point", interagindo com outro casal ou pessoa.', category: 'exposicao', intensity: 6 }, // Variante interação
  { id: 'c331', text: 'Visitar gloryhole (real) para observar anonimamente.', category: 'exposicao', intensity: 4 },
  { id: 'c332', text: 'Visitar gloryhole (real) para interagir anonimamente (um parceiro).', category: 'exposicao', intensity: 6 },
  { id: 'c333', text: 'Visitar gloryhole (real) com o casal participando ou um observando o outro.', category: 'exposicao', intensity: 6 },
  { id: 'c334', text: 'Gloryhole simulado em casa: convidar amigo(a) para interagir com um, outro assiste.', category: 'exposicao', intensity: 5 },
  { id: 'c335', text: 'Gloryhole simulado em casa para uma festa íntima, com vários usando/observando.', category: 'exposicao', intensity: 6 },
  { id: 'c336', text: 'Marido assiste esposa com convidada.', category: 'exposicao', intensity: 5 },
  { id: 'c337', text: 'Marido assiste esposa com um grupo de convidadas.', category: 'exposicao', intensity: 6 },
  { id: 'c338', text: 'Esposa assiste marido com convidado.', category: 'exposicao', intensity: 5 },
  { id: 'c339', text: 'Esposa assiste marido com um grupo de convidados.', category: 'exposicao', intensity: 6 },
  { id: 'c340', text: 'Casal (lésbico) convida amigo para MFF.', category: 'exposicao', intensity: 5 },
  { id: 'c341', text: 'Casal (lésbico) convida alguns amigos para uma experiência MFFF/grupo.', category: 'exposicao', intensity: 6 },
  { id: 'c342', text: 'Casal (gay) convida amiga para MMF.', category: 'exposicao', intensity: 5 },
  { id: 'c343', text: 'Casal (gay) convida algumas amigas para uma experiência MMFF/grupo.', category: 'exposicao', intensity: 6 },
  { id: 'c344', text: 'Troca de casais (swing) apenas com beijos e carícias com outro casal.', category: 'exposicao', intensity: 4 },
  { id: 'c345', text: 'Troca de casais (swing) completa com outro casal amigo, em ambiente privado.', category: 'exposicao', intensity: 6 },
  { id: 'c346', text: 'Participar de uma festa de swing com múltiplos casais.', category: 'exposicao', intensity: 6 },
  { id: 'c347', text: '"Strip quiz" ou prendas eróticas com amigos(as) convidados, com nudez progressiva.', category: 'exposicao', intensity: 4 },
  { id: 'c348', text: 'Um(a) parceiro(a) se masturba enquanto outro(a) e convidado(s) assistem/encorajam.', category: 'exposicao', intensity: 5 },
  { id: 'c349', text: 'Usar plug anal vibratório remoto em passeio em parque/shopping.', category: 'exposicao', intensity: 4 },
  { id: 'c350', text: 'Parceiro(a) tira fotos suas nu(a)/seminu(a) em locais públicos desertos.', category: 'exposicao', intensity: 3 },
  { id: 'c351', text: 'Conversa explícita sobre sexo/fetiches em café, podendo ser ouvida por perto.', category: 'exposicao', intensity: 2 },
  { id: 'c352', text: 'Um(a) parceiro(a) se exibe da janela de casa para a rua (discreto, seguro).', category: 'exposicao', intensity: 3 },
  { id: 'c353', text: 'Ir a balada liberal/festa fetichista juntos, para observar.', category: 'exposicao', intensity: 3 },
  { id: 'c354', text: 'Ir a balada liberal/festa fetichista juntos e interagir com um terceiro.', category: 'exposicao', intensity: 4 },
  { id: 'c355', text: 'Ir a balada liberal/festa fetichista juntos e participar de atividades em grupo.', category: 'exposicao', intensity: 5 },
  { id: 'c356', text: 'Gravar áudio com fantasia erótica e enviar para parceiro(a) (ou grupo íntimo).', category: 'exposicao', intensity: 3 },
  { id: 'c357', text: '"Sexting" com parceiro(a) enquanto ambos estão em eventos sociais separados.', category: 'exposicao', intensity: 2 },
  { id: 'c358', text: 'Esconder-se para observar parceiro(a) se masturbar (com revelação/consentimento posterior).', category: 'exposicao', intensity: 4 },
  { id: 'c359', text: 'Deixar rastro de lingerie pela casa para parceiro(a) (ou visita) seguir.', category: 'exposicao', intensity: 2 },
  { id: 'c360', text: 'Videochamada sensual com parceiro(a) em local semi-público (banheiro de bar).', category: 'exposicao', intensity: 3 },
  { id: 'c361', text: 'Escrever fantasia erótica e publicá-la anonimamente em fórum online.', category: 'exposicao', intensity: 3 },
  { id: 'c362', text: 'Usar roupa transparente sem sutiã ou com lingerie à mostra em evento com parceiro(a).', category: 'exposicao', intensity: 3 },
  { id: 'c363', text: 'Comprar lingerie sensual juntos e fazer "desfile particular" em casa.', category: 'exposicao', intensity: 1 },
  { id: 'c364', text: 'Tirar "nudes discretas" (sem rosto) em locais públicos e enviar ao(à) parceiro(a).', category: 'exposicao', intensity: 4 },
  { id: 'c365', text: 'Parceiro(a) amarra você levemente e fotografa em poses sensuais.', category: 'exposicao', intensity: 3 },
  { id: 'c366', text: 'Dar "flash" rápido (seios/genitais) para parceiro(a) em local inesperado.', category: 'exposicao', intensity: 2 },
  { id: 'c367', text: 'Contar para amigo(a) de confiança detalhe íntimo/fetiche do casal.', category: 'exposicao', intensity: 2 },
  { id: 'c368', text: 'Sexo com luz de abajur projetando sombras na parede/cortina (visível de fora).', category: 'exposicao', intensity: 4 },
  { id: 'c369', text: 'Parceira usa vestido sem calcinha em evento, provocando parceiro com toques.', category: 'exposicao', intensity: 3 },
  { id: 'c370', text: 'Parceiro usa calça justa sem cueca, provocando parceira com volume.', category: 'exposicao', intensity: 3 },
  { id: 'c371', text: '"Noite de confissões sexuais" com amigos íntimos, talvez algumas se realizem.', category: 'exposicao', intensity: 5 },
  { id: 'c372', text: 'Ir a bar de strip/show burlesco juntos e discutir o que acharam excitante.', category: 'exposicao', intensity: 2 },
  { id: 'c373', text: 'Fazer tatuagem/piercing íntimo e revelar sensualmente ao(à) parceiro(a).', category: 'exposicao', intensity: 3 },
  { id: 'c374', text: 'Um(a) vendado(a), outro(a) descreve como terceiro(s) (imaginário/real) o(a) seduz/toca.', category: 'exposicao', intensity: 4 },
  { id: 'c375', text: 'Deixar porta do quarto de hotel entreaberta durante sexo, com placa "não perturbe".', category: 'exposicao', intensity: 3 },
  { id: 'c376', text: 'Usar vibrador remoto enquanto casal está em cinema/teatro.', category: 'exposicao', intensity: 4 },
  { id: 'c377', text: 'Jantar fora e trocar bilhetes com propostas eróticas por baixo da mesa.', category: 'exposicao', intensity: 1 },
  { id: 'c378', text: 'Voyeurismo consensual: um parceiro se esconde para observar o outro tomar banho/se trocar.', category: 'exposicao', intensity: 2 },
  { id: 'c379', text: 'Beijos e carícias intensas em pista de dança escura, talvez envolvendo um terceiro.', category: 'exposicao', intensity: 5 },
  { id: 'c380', text: 'Deixar o(a) parceiro(a) (ou um grupo) escrever palavras/desenhos eróticos no seu corpo.', category: 'exposicao', intensity: 4 },
  { id: 'c381', text: 'Em festa liberal, ter corpo usado como "placar", com parceiros(as) marcando quantos interagiram.', category: 'exposicao', intensity: 6 },
  { id: 'c382', text: 'Sexo em barraca de camping em local movimentado (praia, festival).', category: 'exposicao', intensity: 4 },
  { id: 'c383', text: 'Tirar foto sensual na cabine de banheiro público e enviar ao(à) parceiro(a).', category: 'exposicao', intensity: 3 },
  { id: 'c384', text: 'Fotografar parceiro(a) em poses sensuais em oficina mecânica/borracharia.', category: 'exposicao', intensity: 3 },
  { id: 'c385', text: 'Exibir-se para parceiro(a) ou sexo rápido no carro em estacionamento subterrâneo.', category: 'exposicao', intensity: 4 },
  { id: 'c386', text: 'Masturbar-se em praça deserta à noite, com parceiro(a) vigiando.', category: 'exposicao', intensity: 4 },
  { id: 'c387', text: 'Desafiar parceiro(a) a tirar peça de roupa em público sem ser notado(a).', category: 'exposicao', intensity: 3 },
  { id: 'c388', text: 'Videochamada sensual com parceiro(a) enquanto ele(a) está no Uber (com fones).', category: 'exposicao', intensity: 2 },
  { id: 'c389', text: 'Provador de loja: experimentar lingerie e enviar fotos ao(à) parceiro(a) (ou grupo).', category: 'exposicao', intensity: 3 },
  { id: 'c390', text: 'Combinar com parceiro(a) de "acidentalmente" se abaixar de forma provocante na frente de entregador/técnico.', category: 'exposicao', intensity: 3 },
  { id: 'c391', text: 'Usar roupas de ginástica justas sem roupa íntima em pista de caminhada.', category: 'exposicao', intensity: 2 },
  { id: 'c392', text: 'Posto de gasolina: parceira abastece com decote ousado, parceiro observa reação.', category: 'exposicao', intensity: 2 },
  { id: 'c393', text: 'No semáforo, beijo de língua cinematográfico para carros ao lado verem.', category: 'exposicao', intensity: 1 },
  { id: 'c394', text: 'Sessão de fotos eróticas do casal em oficina abandonada/cenário industrial.', category: 'exposicao', intensity: 4 },
  { id: 'c395', text: 'Tomar banho nu(a) em rio/lago remoto, parceiro(a) vigia.', category: 'exposicao', intensity: 3 },
  { id: 'c396', text: 'Usar roupa de academia reveladora, provocando parceiro(a) (ou outros).', category: 'exposicao', intensity: 2 },
  { id: 'c397', text: 'Trocar olhares/toques "acidentais" no vestiário da academia.', category: 'exposicao', intensity: 2 },
  { id: 'c398', text: 'Sauna mista: carícias quentes com parceiro(a), cientes de outros olhares.', category: 'exposicao', intensity: 4 },
  { id: 'c399', text: 'Ser filmado(a) pelo(a) parceiro(a) se exercitando de forma sensual e compartilhar com um(a) amigo(a) ou grupo online.', category: 'exposicao', intensity: 4 },
  { id: 'c400', text: 'Trocar carícias ousadas por baixo de um casaco em ônibus/metrô lotado.', category: 'exposicao', intensity: 3 },
  { id: 'c401', text: 'Deixar mão do(a) parceiro(a) "deslizar" para lugares proibidos em viagem de trem.', category: 'exposicao', intensity: 3 },
  { id: 'c402', text: 'Atingir orgasmo com vibrador discreto em transporte público, parceiro(a) dá cobertura.', category: 'exposicao', intensity: 4 },
  { id: 'c403', text: 'Deixar bilhete indecente em livro para parceiro(a) achar na biblioteca/livraria.', category: 'exposicao', intensity: 1 },
  { id: 'c404', text: 'Beijos e carícias escondidos entre estantes de biblioteca/livraria.', category: 'exposicao', intensity: 2 },
  { id: 'c405', text: 'Sussurrar comentários eróticos no ouvido do(a) parceiro(a) durante concerto/peça.', category: 'exposicao', intensity: 1 },
  { id: 'c406', text: 'Trocar toques discretos e ousados por baixo da roupa em visita a museu.', category: 'exposicao', intensity: 2 },

  // --- CATEGORIA: CONEXÃO (c407 - c456) ---
  { id: 'c407', text: 'Elogie sinceramente uma qualidade que admira no seu parceiro(a) hoje.', category: 'conexao' },
  { id: 'c408', text: 'Prepare a bebida favorita do seu parceiro(a) de surpresa.', category: 'conexao' },
  { id: 'c409', text: 'Envie mensagem carinhosa e inesperada durante o dia de trabalho dele(a).', category: 'conexao' },
  { id: 'c410', text: 'Deixe um bilhete amoroso escrito à mão onde ele(a) certamente encontrará.', category: 'conexao' },
  { id: 'c411', text: 'Pergunte sobre o dia do seu parceiro(a) e ouça com total atenção.', category: 'conexao' },
  { id: 'c412', text: 'Ofereça massagem de 10 min nos ombros/pés, sem esperar nada em troca.', category: 'conexao' },
  { id: 'c413', text: "Diga 'Eu te amo' de forma especial ou em momento inesperado hoje.", category: 'conexao' },
  { id: 'c414', text: 'Planejem juntos um momento a sós para o fim de semana, sem celulares.', category: 'conexao' },
  { id: 'c415', text: 'Relembrem em voz alta uma memória engraçada ou feliz que viveram juntos.', category: 'conexao' },
  { id: 'c416', text: 'Façam uma gentileza um pelo(a) outro(a) que alivie uma tarefa ou preocupação.', category: 'conexao' },
  { id: 'c417', text: 'Dê um abraço apertado e demorado (mais de 10s!) sem motivo.', category: 'conexao' },
  { id: 'c418', text: 'Escreva 3 coisas que mais ama no seu parceiro(a) e entregue a ele(a).', category: 'conexao' },
  { id: 'c419', text: "Escolham juntos uma música que seja 'a cara de vocês' e ouçam com atenção.", category: 'conexao' },
  { id: 'c420', text: 'Segure a mão do(a) parceiro(a) carinhosamente enquanto assistem TV ou caminham.', category: 'conexao' },
  { id: 'c421', text: 'Agradeça especificamente por algo (grande/pequeno) que seu parceiro(a) fez por você.', category: 'conexao' },
  { id: 'c422', text: 'Faça um carinho no cabelo ou rosto dele(a) de forma espontânea.', category: 'conexao' },
  { id: 'c423', text: 'Compartilhem um pequeno sonho ou desejo individual para o futuro próximo.', category: 'conexao' },
  { id: 'c424', text: 'Preparem juntos o café da manhã ou um lanche especial no fim de semana.', category: 'conexao' },
  { id: 'c425', text: 'Olhem fotos antigas de vocês e conversem sobre as boas lembranças.', category: 'conexao' },
  { id: 'c426', text: 'Reserve 15 min hoje para conversarem sem interrupções, sobre vocês.', category: 'conexao' },
  { id: 'c427', text: 'Compartilhem um segredo que nunca contaram a ninguém (um com o outro).', category: 'conexao' },
  { id: 'c428', text: 'Escolham um novo hobby ou atividade para aprenderem juntos este mês.', category: 'conexao' },
  { id: 'c429', text: 'Caminhem de mãos dadas e conversem sobre seus sonhos para o futuro do casal.', category: 'conexao' },
  { id: 'c430', text: 'Cozinhem uma refeição especial juntos, dividindo tarefas e aproveitando.', category: 'conexao' },
  { id: 'c431', text: 'Escrevam uma carta um para o outro expressando admiração e amor na relação.', category: 'conexao' },
  { id: 'c432', text: 'Passem uma noite sem eletrônicos, apenas conversando ou lendo juntos.', category: 'conexao' },
  { id: 'c433', text: 'Planejem uma "aventura" local no fds (parque novo, cafeteria).', category: 'conexao' },
  { id: 'c434', text: 'Listem 5 coisas pelas quais são gratos um pelo outro e compartilhem.', category: 'conexao' },
  { id: 'c435', text: 'Crie um "pote de momentos felizes": escrevam momentos bons para lerem no futuro.', category: 'conexao' },
  { id: 'c436', text: 'Dê feedback positivo e específico sobre algo que seu/sua parceiro(a) fez e te alegrou.', category: 'conexao' },
  { id: 'c437', text: 'Reservem 30 min para se abraçarem em silêncio, sentindo a presença um do outro.', category: 'conexao' },
  { id: 'c438', text: 'Aprendam nova habilidade juntos online (culinária, dança).', category: 'conexao' },
  { id: 'c439', text: 'Surpreenda seu/sua parceiro(a) com o doce/snack favorito dele(a).', category: 'conexao' },
  { id: 'c440', text: 'Assistam ao nascer ou pôr do sol juntos, em silêncio ou conversando.', category: 'conexao' },
  { id: 'c441', text: 'Façam "dia do elogio": procurem oportunidades para elogiar um ao outro.', category: 'conexao' },
  { id: 'c442', text: 'Escolham causa/instituição de caridade para apoiarem juntos.', category: 'conexao' },
  { id: 'c443', text: 'Recordem juntos como se conheceram e o que os atraiu no início.', category: 'conexao'},
  { id: 'c444', text: 'Ofereça ajuda em uma tarefa que seu/sua parceiro(a) não gosta de fazer.', category: 'conexao'},
  { id: 'c445', text: 'Enviem um ao outro música que expresse seus sentimentos sobre a relação.', category: 'conexao'},
  { id: 'c446', text: 'Criem "cápsula do tempo" do casal (fotos, bilhetes) para abrir em 5-10 anos.', category: 'conexao'},
  { id: 'c447', text: 'Dediquem noite para cuidar um do outro (banho, massagem, chá especial).', category: 'conexao'},
  { id: 'c448', text: 'Compartilhar banho e lavar o corpo um do outro lentamente.', category: 'conexao' },
  { id: 'c449', text: 'Dedicar 20 min para olhar nos olhos um do outro sem falar.', category: 'conexao' },
  { id: 'c450', text: 'Escolham livro (não erótico) e leiam capítulos em voz alta um para o outro.', category: 'conexao' },
  { id: 'c451', text: 'Planejem e realizem "encontro dos sonhos" um para o outro.', category: 'conexao' },
  { id: 'c452', text: 'Criem código secreto/linguagem corporal para comunicar "penso em você" em público.', category: 'conexao' },
  { id: 'c453', text: 'Sejam "turistas na própria cidade", explorando lugares novos de mãos dadas.', category: 'conexao' },
  { id: 'c454', text: 'Criem "ritual de conexão" diário/semanal (compartilhar 3 coisas boas do dia).', category: 'conexao' },
  { id: 'c455', text: 'Assistir workshop/palestra online sobre comunicação/intimidade e discutir.', category: 'conexao' },
  { id: 'c456', text: 'Definam "noite de tecnologia zero" semanal para foco total um no outro.', category: 'conexao' },
  { id: 'c457', text: 'Façam uma lista de desejos do casal para realizar juntos nos próximos meses.', category: 'conexao' },
  { id: 'c458', text: 'Faça uma retrospectiva do último ano e discuta o que deu certo e o que precisa melhorar.', category: 'conexao' },
  { id: 'c459', text: 'Faça uma lista de coisas que vocês gostariam de fazer juntos no futuro.', category: 'conexao' },






];

// Exporta o array DIRETAMENTE para que o script de upload possa usá-lo.
module.exports = allKinkLinkCards;