// d:\Projetos\Github\app\ProjectKinkLink\KinkLink\src\components\categorySpecificTips.ts
import type { Card } from '../data/cards'; // Assuming Card type is exported from here

type TipSet = { left: string[]; right: string[] };
export const categorySpecificTips: Record<Card['category'] | 'default', TipSet> = {
    poder: {
      left: [
        "cardTips.poder.left.0",
        "cardTips.poder.left.1",
        "cardTips.poder.left.2",
        "cardTips.poder.left.3",
        "cardTips.poder.left.4",
        "cardTips.poder.left.5",
        "cardTips.poder.left.6",
        "cardTips.poder.left.7",
        "cardTips.poder.left.8",
        "cardTips.poder.left.9",
        "cardTips.poder.left.10",
        "cardTips.poder.left.11",
        "cardTips.poder.left.12",
        "cardTips.poder.left.13",
        "cardTips.poder.left.14",
        "cardTips.poder.left.15",
        "cardTips.poder.left.16",
        "cardTips.poder.left.17",
        "cardTips.poder.left.18",
        "cardTips.poder.left.19"
      ],
      right: [
        "cardTips.poder.right.0",
        "cardTips.poder.right.1",
        "cardTips.poder.right.2",
        "cardTips.poder.right.3",
        "cardTips.poder.right.4",
        "cardTips.poder.right.5",
        "cardTips.poder.right.6",
        "cardTips.poder.right.7",
        "cardTips.poder.right.8",
        "cardTips.poder.right.9",
        "cardTips.poder.right.10",
        "cardTips.poder.right.11",
        "cardTips.poder.right.12",
        "cardTips.poder.right.13",
        "cardTips.poder.right.14",
        "cardTips.poder.right.15",
        "cardTips.poder.right.16",
        "cardTips.poder.right.17",
        "cardTips.poder.right.18",
        "cardTips.poder.right.19"
      ],
    },
    sensorial: {
      left: [
        "cardTips.sensorial.left.0",
        "cardTips.sensorial.left.1",
        "cardTips.sensorial.left.2",
        "cardTips.sensorial.left.3",
        "cardTips.sensorial.left.4",
        "cardTips.sensorial.left.5",
        "cardTips.sensorial.left.6",
        "cardTips.sensorial.left.7",
        "cardTips.sensorial.left.8",
        "cardTips.sensorial.left.9",
        "cardTips.sensorial.left.10",
        "cardTips.sensorial.left.11",
        "cardTips.sensorial.left.12",
        "cardTips.sensorial.left.13",
        "cardTips.sensorial.left.14",
        "cardTips.sensorial.left.15",
        "cardTips.sensorial.left.16",
        "cardTips.sensorial.left.17",
        "cardTips.sensorial.left.18",
        "cardTips.sensorial.left.19"
      ],
      right: [
        "cardTips.sensorial.right.0",
        "cardTips.sensorial.right.1",
        "cardTips.sensorial.right.2",
        "cardTips.sensorial.right.3",
        "cardTips.sensorial.right.4",
        "cardTips.sensorial.right.5",
        "cardTips.sensorial.right.6",
        "cardTips.sensorial.right.7",
        "cardTips.sensorial.right.8",
        "cardTips.sensorial.right.9",
        "cardTips.sensorial.right.10",
        "cardTips.sensorial.right.11",
        "cardTips.sensorial.right.12",
        "cardTips.sensorial.right.13",
        "cardTips.sensorial.right.14",
        "cardTips.sensorial.right.15",
        "cardTips.sensorial.right.16",
        "cardTips.sensorial.right.17",
        "cardTips.sensorial.right.18",
        "cardTips.sensorial.right.19"
      ],
    },
    fantasia: {
      left: [
        "cardTips.fantasia.left.0",
        "cardTips.fantasia.left.1",
        "cardTips.fantasia.left.2",
        "cardTips.fantasia.left.3",
        "cardTips.fantasia.left.4",
        "cardTips.fantasia.left.5",
        "cardTips.fantasia.left.6",
        "cardTips.fantasia.left.7",
        "cardTips.fantasia.left.8",
        "cardTips.fantasia.left.9",
        "cardTips.fantasia.left.10",
        "cardTips.fantasia.left.11",
        "cardTips.fantasia.left.12",
        "cardTips.fantasia.left.13",
        "cardTips.fantasia.left.14",
        "cardTips.fantasia.left.15",
        "cardTips.fantasia.left.16",
        "cardTips.fantasia.left.17",
        "cardTips.fantasia.left.18",
        "cardTips.fantasia.left.19"
      ],
      right: [
        "cardTips.fantasia.right.0",
        "cardTips.fantasia.right.1",
        "cardTips.fantasia.right.2",
        "cardTips.fantasia.right.3",
        "cardTips.fantasia.right.4",
        "cardTips.fantasia.right.5",
        "cardTips.fantasia.right.6",
        "cardTips.fantasia.right.7",
        "cardTips.fantasia.right.8",
        "cardTips.fantasia.right.9",
        "cardTips.fantasia.right.10",
        "cardTips.fantasia.right.11",
        "cardTips.fantasia.right.12",
        "cardTips.fantasia.right.13",
        "cardTips.fantasia.right.14",
        "cardTips.fantasia.right.15",
        "cardTips.fantasia.right.16",
        "cardTips.fantasia.right.17",
        "cardTips.fantasia.right.18",
        "cardTips.fantasia.right.19"
      ],
    },
    exposicao: {
      left: [
        "cardTips.exposicao.left.0",
        "cardTips.exposicao.left.1",
        "cardTips.exposicao.left.2",
        "cardTips.exposicao.left.3",
        "cardTips.exposicao.left.4",
        "cardTips.exposicao.left.5",
        "cardTips.exposicao.left.6",
        "cardTips.exposicao.left.7",
        "cardTips.exposicao.left.8",
        "cardTips.exposicao.left.9",
        "cardTips.exposicao.left.10",
        "cardTips.exposicao.left.11",
        "cardTips.exposicao.left.12",
        "cardTips.exposicao.left.13",
        "cardTips.exposicao.left.14",
        "cardTips.exposicao.left.15",
        "cardTips.exposicao.left.16",
        "cardTips.exposicao.left.17",
        "cardTips.exposicao.left.18",
        "cardTips.exposicao.left.19"
      ],
      right: [
        "cardTips.exposicao.right.0",
        "cardTips.exposicao.right.1",
        "cardTips.exposicao.right.2",
        "cardTips.exposicao.right.3",
        "cardTips.exposicao.right.4",
        "cardTips.exposicao.right.5",
        "cardTips.exposicao.right.6",
        "cardTips.exposicao.right.7",
        "cardTips.exposicao.right.8",
        "cardTips.exposicao.right.9",
        "cardTips.exposicao.right.10",
        "cardTips.exposicao.right.11",
        "cardTips.exposicao.right.12",
        "cardTips.exposicao.right.13",
        "cardTips.exposicao.right.14",
        "cardTips.exposicao.right.15",
        "cardTips.exposicao.right.16",
        "cardTips.exposicao.right.17",
        "cardTips.exposicao.right.18",
        "cardTips.exposicao.right.19"
      ],
    },
    conexao: {
      left: [
        "cardTips.conexao.left.0",
        "cardTips.conexao.left.1",
        "cardTips.conexao.left.2",
        "cardTips.conexao.left.3",
        "cardTips.conexao.left.4"
      ],
      right: [
        "cardTips.conexao.right.0",
        "cardTips.conexao.right.1",
        "cardTips.conexao.right.2",
        "cardTips.conexao.right.3",
        "cardTips.conexao.right.4"
      ],
    },
    default: {
      left: [
        "cardTips.default.left.0",
        "cardTips.default.left.1",
        "cardTips.default.left.2",
        "cardTips.default.left.3",
        "cardTips.default.left.4"
      ],
      right: [
        "cardTips.default.right.0",
        "cardTips.default.right.1",
        "cardTips.default.right.2",
        "cardTips.default.right.3",
        "cardTips.default.right.4"
      ],
    },
};